begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(4);
select throws_ok($q$select public.create_cafe_ticket_booking_request('individual', current_date + 90, '15:29', 45, 1, 1, array['laser-tag'])$q$, 'P0001', 'Selected time is outside Vrena Thao Dien opening hours.', 'CS rejects starts before 15:30');
select throws_ok($q$select public.create_cafe_ticket_booking_request('individual', current_date + 90, '15:30', 45, 1, 1, array['laser-tag'])$q$, 'P0001', 'Enter a valid phone number.', 'CS accepts 15:30 and proceeds to guest validation');
select throws_ok($q$select public.create_cafe_ticket_booking_request('individual', current_date + 90, '22:15', 45, 1, 1, array['laser-tag'])$q$, 'P0001', 'Enter a valid phone number.', 'CS accepts a session ending at 23:00');
select throws_ok($q$select public.create_cafe_ticket_booking_request('individual', current_date + 90, '22:16', 45, 1, 1, array['laser-tag'])$q$, 'P0001', 'Selected time is outside Vrena Thao Dien opening hours.', 'CS rejects sessions ending after 23:00');
select * from finish();
rollback;
