begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select set_config('request.jwt.claims','{"role":"service_role"}',true);
insert into auth.users(id,email) values('86000000-0000-4000-8000-000000000001','calendar-admin@example.invalid');
insert into public.profiles(id,full_name,role) values('86000000-0000-4000-8000-000000000001','Calendar test admin','admin') on conflict(id) do update set role='admin';
insert into auth.mfa_factors(id,user_id,factor_type,status,secret,created_at,updated_at) values('86000000-0000-4000-8000-000000000002','86000000-0000-4000-8000-000000000001','totp','verified','LOCAL-TEST-ONLY',now(),now());
insert into public.staff_games(slug,name,game_type,duration_minutes,max_players_per_arena,available_arena_ids,active) values('city-z','City Z','shooting',45,6,array['arena-1','arena-2'],true) on conflict(slug) do update set active=true;
create temp table calendar_results(label text,result jsonb);
grant all on calendar_results to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"role":"authenticated","sub":"86000000-0000-4000-8000-000000000001","aal":"aal2"}',true);
insert into calendar_results values('booking',public.staff_create_booking(jsonb_build_object('p_game_id',(select id from public.staff_games where slug='city-z'),'p_booking_date',current_date+92,'p_booking_time','16:00','p_players_count',1,'p_arena_id','cafe:arena-1','p_order_status','confirmed','p_payment_splits',jsonb_build_array(jsonb_build_object('payment_method','cash','amount',100000))),'zalo'));
select is((select booking_source from public.staff_orders where id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),'zalo','Booking source is recorded with the order');
select throws_ok($q$select public.staff_create_booking('{}','invalid')$q$,'P0001','Invalid booking source.','Invalid source cannot create an order');
insert into calendar_results values('patch',jsonb_build_object('name','Calendar edited booking','date',current_date+93,'start_time','17:00','duration_minutes',45,'players',2,'arena_count',1,'arena_id','arena-2','venue_key','ha-do-centrosa','game_slug','city-z','status','open','booking_source','whatsapp'));
select lives_ok($q$select public.staff_update_calendar_booking((select (result->>'session_id')::uuid from calendar_results where label='booking'),(select result from calendar_results where label='patch'))$q$,'Staff can move a booking between shops and dates');
select is((select venue_key from public.sessions where id=(select (result->>'session_id')::uuid from calendar_results where label='booking')),'ha-do-centrosa','New shop is saved');
select is((select booking_date from public.staff_orders where id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),current_date+93,'Linked order date moves with the booking');
select is((select booking_time::time from public.staff_orders where id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),'17:00'::time,'Linked order time moves with the booking');
select is((select players_count from public.staff_orders where id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),2,'Linked order player count stays consistent');
select is((select booking_source from public.staff_orders where id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),'whatsapp','Source can be corrected');
select is((select total from public.staff_orders where id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),240000,'Agreed price is preserved');
select is((select sum(amount)::int from public.staff_order_payments where order_id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),100000,'Recorded payments are preserved');
select throws_ok($q$select public.staff_update_calendar_booking((select (result->>'session_id')::uuid from calendar_results where label='booking'),(select result||'{"expected_updated_at":"2000-01-01T00:00:00Z"}'::jsonb from calendar_results where label='patch'))$q$,'P0001','This booking has changed. Close and reopen it before saving.','Stale edit is rejected');
insert into calendar_results values('neighbour',public.create_staff_order_with_payments(null,null,null,null,(select id from public.staff_games where slug='city-z'),current_date+93,'17:00',1,'arena-1',null,'confirmed'));
select throws_ok($q$select public.staff_update_calendar_booking((select (result->>'session_id')::uuid from calendar_results where label='booking'),(select result||'{"arena_id":"arena-1"}'::jsonb from calendar_results where label='patch'))$q$,'P0001','This arena is already booked at the selected time. Choose another arena or time.','Occupied arena is rejected');
select throws_ok($q$select public.staff_update_calendar_booking((select (result->>'session_id')::uuid from calendar_results where label='booking'),(select result||'{"venue_key":"cafe-des-stagiaires","start_time":"09:00"}'::jsonb from calendar_results where label='patch'))$q$,'P0001','Selected time is outside opening hours.','Cafe hours are enforced on edits');
select set_config('request.jwt.claims','{"role":"authenticated","sub":"86000000-0000-4000-8000-000000000001","aal":"aal1"}',true);
select throws_ok($q$select public.staff_update_calendar_booking((select (result->>'session_id')::uuid from calendar_results where label='booking'),(select result from calendar_results where label='patch'))$q$,'P0001','Staff access required.','AAL1 cannot edit calendar bookings');
select throws_ok($q$select public.staff_create_booking('{}','walk_in')$q$,'P0001','Staff access required.','AAL1 cannot use source-aware creation');
select set_config('request.jwt.claims','{"role":"authenticated","sub":"86000000-0000-4000-8000-000000000001","aal":"aal2"}',true);
select lives_ok($q$select public.staff_delete_session_operation((select (result->>'session_id')::uuid from calendar_results where label='booking'),'Calendar deletion test')$q$,'Calendar deletion uses the scoped staff deletion');
select ok((select deleted_at is null from public.sessions where id=(select (result->>'session_id')::uuid from calendar_results where label='neighbour')),'Deleting one booking leaves its neighbour intact');
select is((select order_status from public.staff_orders where id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),'cancelled','Deleted booking order is cancelled');
select is((select sum(amount)::int from public.staff_order_payments where order_id=(select (result->>'order_id')::uuid from calendar_results where label='booking')),100000,'Deletion retains actual payments');
reset role;
select ok(not has_function_privilege('anon','public.staff_update_calendar_booking(uuid,jsonb)','execute'),'Anonymous cannot execute calendar edits');
select ok(not has_function_privilege('anon','public.staff_create_booking(jsonb,text)','execute'),'Anonymous cannot create staff bookings');
select ok(not (select prosecdef from pg_proc where oid='public.staff_update_calendar_booking(uuid,jsonb)'::regprocedure),'Public edit wrapper uses invoker rights');
select * from finish();
rollback;
