import { expect, test } from '@playwright/test'
import { createClient } from '@supabase/supabase-js'
import { futureDate, loginAsAdmin, openAdmin } from './support/admin'

test('staff orders: split receipts, shop transfer, price reason and no-show stay consistent', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'chromium', 'One isolated write fixture; desktop and mobile checked together.')
  if (process.env.SUPABASE_URL !== 'http://127.0.0.1:56431') throw new Error('Orders write tests require isolated services.')
  const admin = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } })
  const date = futureDate(210)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  let sessionId: string | undefined
  let orderId: string | undefined
  try {
    await loginAsAdmin(page)
    await openAdmin(page)
    await page.setViewportSize({ width: 1142, height: 894 })
    await page.getByRole('checkbox', { name: 'Guest booking', exact: true }).check()
    await page.getByRole('combobox', { name: 'Shop', exact: true }).selectOption('cafe-des-stagiaires')
    await page.getByRole('combobox', { name: 'Game', exact: true }).selectOption({ label: 'City Z' })
    await page.getByLabel('Booking date', { exact: true }).fill(date)
    const creation = page.waitForResponse((res) => res.url().endsWith('/rpc/staff_create_booking'))
    await page.getByRole('button', { name: 'Confirm booking', exact: true }).click()
    const created = await (await creation).json()
    sessionId = created.session_id
    orderId = created.order_id
    expect(sessionId).toBeTruthy()
    const initial = await admin.from('staff_orders').select('*').eq('id', created.order_id).single()
    expect(initial.error).toBeNull()
    const orderNumber = initial.data!.order_number
    await page.getByRole('tab', { name: 'Orders', exact: true }).click()
    await page.getByRole('textbox', { name: 'Start date', exact: true }).fill(date)
    await page.getByRole('textbox', { name: 'End date', exact: true }).fill(date)
    await page.getByRole('button', { name: 'Show orders', exact: true }).click()
    const row = page.getByRole('row').filter({ has: page.getByText(orderNumber, { exact: true }) }).first()
    await expect(row).toContainText('Café des Stagiaires')
    await row.getByRole('button', { name: 'Payment', exact: true }).click()
    const payment = page.getByRole('form', { name: 'Record order payment', exact: true })
    await payment.getByRole('spinbutton').fill('40000')
    await payment.getByRole('button', { name: 'Add split', exact: true }).click()
    await payment.getByRole('combobox').nth(1).selectOption('card_manual')
    await payment.getByRole('spinbutton').nth(1).fill('300000')
    await expect(payment.getByRole('button', { name: 'Save order payment', exact: true })).toBeDisabled()
    await payment.getByRole('spinbutton').nth(1).fill('60000')
    await expect(payment).toContainText('Remaining after save: 140.000')
    await page.setViewportSize({ width: 375, height: 667 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await payment.scrollIntoViewIfNeeded()
    await page.screenshot({ path: '/tmp/staff-orders-mobile.png', animations: 'disabled' })
    await page.setViewportSize({ width: 1142, height: 894 })
    let simulateLostResponse = true
    await page.route('**/rpc/staff_record_order_payments', async (route) => {
      const response = await route.fetch()
      if (simulateLostResponse) { simulateLostResponse = false; await route.abort('failed') }
      else await route.fulfill({ response })
    })
    await payment.getByRole('button', { name: 'Save order payment', exact: true }).click()
    await expect(payment.getByRole('alert')).toBeVisible()
    await expect(payment.getByRole('spinbutton').first()).toBeDisabled()
    await payment.getByRole('button', { name: 'Save order payment', exact: true }).click()
    await expect(payment).toHaveCount(0)
    await row.getByText('Payment details', { exact: true }).click()
    await expect(row).toContainText('Credit/Debit Card · 60.000')
    await expect(row).toContainText('Paid: 100.000')
    await row.getByRole('button', { name: 'Edit booking / Move shop', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Edit booking', exact: true })
    await dialog.getByRole('combobox', { name: 'Shop', exact: true }).selectOption('ha-do-centrosa')
    await expect(dialog.getByRole('combobox', { name: 'Game', exact: true })).toHaveValue('city-z')
    await dialog.getByRole('textbox', { name: 'Time', exact: true }).fill('17:00')
    await dialog.getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await expect(row).toContainText('Hà Đô Centrosa')
    await expect(row).toContainText('17:00')
    await expect(row).toContainText('Paid: 100.000')
    expect(await row.getByRole('button', { name: 'Adjust total', exact: true }).evaluate((button) => getComputedStyle(button).borderTopWidth)).toBe('0px')
    await row.getByRole('button', { name: 'Adjust total', exact: true }).click()
    const reason = page.getByRole('textbox', { name: 'Reason for price adjustment', exact: true })
    await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
    await page.getByRole('spinbutton', { name: 'Total', exact: true }).fill('300000')
    await reason.fill('Agreed package after shop transfer')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(reason).toHaveCount(0)
    await expect(row).toContainText('Balance: 200.000')
    await page.screenshot({ path: '/tmp/staff-orders-desktop.png', animations: 'disabled' })
    await page.getByRole('tab', { name: 'Today', exact: true }).click()
    await page.getByRole('textbox', { name: 'Operations date', exact: true }).fill(date)
    await page.getByRole('button', { name: 'Edit booking / Move shop', exact: true }).click()
    await expect(dialog.getByRole('combobox', { name: 'Shop', exact: true })).toHaveValue('ha-do-centrosa')
    await dialog.getByRole('button', { name: 'Close', exact: true }).last().click()
    await page.getByRole('tab', { name: 'Orders', exact: true }).click()
    await row.getByRole('button', { name: 'Mark completed', exact: true }).click()
    const completion = page.getByRole('group', { name: 'Mark completed', exact: true })
    await expect(completion).toContainText('Outstanding balance: 200.000')
    await completion.getByRole('button', { name: 'Cancel', exact: true }).click()
    await row.getByRole('button', { name: 'No-show', exact: true }).click()
    await page.getByRole('button', { name: 'Confirm no-show', exact: true }).click()
    await expect(row.getByRole('button', { name: 'Payment', exact: true })).toBeDisabled()
    const order = await admin.from('staff_orders').select('total,arena_id,booking_time,order_status,payment_method,price_override_reason,staff_order_payments(amount,payment_method)').eq('id', created.order_id).single()
    expect(order.data).toMatchObject({ total: 300000, arena_id: 'arena-1', booking_time: '17:00:00', order_status: 'no_show', payment_method: 'split', price_override_reason: 'Agreed package after shop transfer' })
    expect(order.data!.staff_order_payments).toHaveLength(2)
    const session = await admin.from('sessions').select('venue_key,status,ticket_total_price').eq('id', sessionId).single()
    expect(session.data).toMatchObject({ venue_key: 'ha-do-centrosa', status: 'cancelled', ticket_total_price: 300000 })
    expect(errors).toEqual([])
  } finally {
    if (orderId) {
      await admin.from('staff_order_payments').delete().eq('order_id', orderId)
      await admin.from('staff_orders').delete().eq('id', orderId)
    }
    if (sessionId) await admin.from('sessions').delete().eq('id', sessionId)
  }
})
