export const staffBookingCopy = {
  en: {
    bookingSource: 'Booking source',
    openingHours: 'Opening hours', latestStart: 'Latest start',
    outsideHours: 'Choose a time within the shop’s opening hours that allows the game to finish before closing.',
    automaticDiscount: 'Automatic group discount',
    groupDiscountHelp: 'Group savings update automatically when the player count changes. Choose the birthday offer when applicable. Offers are not combined.',
    overrideTotal: 'Override total',
    finalTotal: 'Final total (VND)',
    overrideReason: 'Reason for price override',
    overrideHelp: 'The reason is required and saved with this booking.',
    invalidOverride: 'Enter a whole VND total of zero or more and a reason for the override.',
    sources: { walk_in: 'Walk-in', zalo: 'Zalo', whatsapp: 'WhatsApp', phone: 'Phone', website: 'Website', other: 'Other' },
    removeSplit: 'Remove payment split',
    bookingType: 'Booking type', customerBooking: 'Client booking', shop: 'Shop',
    searchCustomer: 'Search by name, phone or email, or enter a new client',
    createProfile: 'Create profile for “{name}”',
    createWithBooking: 'New client? Enter their name and optional contact details. The profile is saved when you confirm this booking.',
    profileSelected: 'Existing profile selected. Contact details below apply to this booking.',
    invalidBooking: 'Enter a valid date, time and player count (1–16).',
    invalidEmail: 'Enter a valid email address or leave it empty.',
    discountChanged: 'This discount no longer applies. Choose an available discount or no discount.',
    discountsHelp: '{count} offers match this game, date, time and player count. Customer usage limits are checked when confirming.',
    discountValue: 'Unique discount value', noGames: 'No games available at this shop',
    durationHelp: 'This staff booking reserves the game runtime shown below. Check the shop, time, players and total before confirming.',
  },
  vi: {
    bookingSource: 'Nguồn đặt chỗ',
    openingHours: 'Giờ mở cửa', latestStart: 'Giờ bắt đầu muộn nhất',
    outsideHours: 'Chọn giờ trong thời gian mở cửa và đủ để hoàn thành trò chơi trước khi đóng cửa.',
    automaticDiscount: 'Tự động giảm giá nhóm',
    groupDiscountHelp: 'Ưu đãi nhóm tự động cập nhật khi thay đổi số người. Chọn ưu đãi sinh nhật khi phù hợp. Không cộng dồn ưu đãi.',
    overrideTotal: 'Điều chỉnh tổng tiền',
    finalTotal: 'Tổng tiền cuối cùng (VND)',
    overrideReason: 'Lý do điều chỉnh giá',
    overrideHelp: 'Bắt buộc nhập lý do. Lý do được lưu cùng đặt chỗ.',
    invalidOverride: 'Nhập tổng tiền VND nguyên không âm và lý do điều chỉnh.',
    sources: { walk_in: 'Khách đến trực tiếp', zalo: 'Zalo', whatsapp: 'WhatsApp', phone: 'Điện thoại', website: 'Website', other: 'Khác' },
    removeSplit: 'Xóa phần thanh toán',
    bookingType: 'Loại đặt chỗ', customerBooking: 'Đặt chỗ theo hồ sơ khách', shop: 'Cửa hàng',
    searchCustomer: 'Tìm theo tên, điện thoại, email hoặc nhập tên khách mới',
    createProfile: 'Tạo hồ sơ cho “{name}”',
    createWithBooking: 'Khách mới? Nhập tên và thông tin liên hệ nếu có. Hồ sơ được lưu khi xác nhận đặt chỗ này.',
    profileSelected: 'Đã chọn hồ sơ có sẵn. Thông tin liên hệ bên dưới áp dụng cho lượt đặt chỗ này.',
    invalidBooking: 'Nhập ngày, giờ và số người chơi hợp lệ (1–16).',
    invalidEmail: 'Nhập email hợp lệ hoặc để trống.',
    discountChanged: 'Ưu đãi này không còn áp dụng. Chọn ưu đãi khác hoặc không giảm giá.',
    discountsHelp: '{count} ưu đãi phù hợp với trò chơi, ngày, giờ và số người. Giới hạn sử dụng theo khách được kiểm tra khi xác nhận.',
    discountValue: 'Giá trị giảm giá riêng', noGames: 'Cửa hàng chưa có trò chơi khả dụng',
    durationHelp: 'Lượt đặt chỗ của nhân viên giữ chỗ theo thời lượng trò chơi bên dưới. Kiểm tra cửa hàng, giờ, số người và tổng tiền trước khi xác nhận.',
  },
} as const
