export const staffBookingCopy = {
  en: {
    noGame: 'None', startTime: 'Starting time', arenaCount: 'Number of arenas',
    totalVatIncluded: 'Total (VAT included)', totalBeforeVat: 'Total before VAT',
    vatNotes: 'Details for VAT invoice:\nCompany name:\nCompany address:\nCompany VAT number:',
    standardBooking: 'Standard game', eventBooking: 'Event / corporate',
    reservedMinutes: 'Time booked (minutes)', endTime: 'End time', reservedTime: 'Total time reserved',
    allowOutsideHours: 'Allow booking outside opening hours',
    eventHelp: 'Enter the full time needed, including preparation and turnaround. Any whole number of minutes is allowed, ending by midnight. Use Override total for an agreed event price.',
    contactName: 'Contact person', contactHelp: 'Enter the company or customer name above, and the person to contact here. Phone and email below are the booking contact details.',
    checkingAvailability: 'Checking arena availability…', available: 'Arena available for the full reserved time.',
    unavailable: 'This arena or time is unavailable. Choose another arena or time.',
    availabilityError: 'Unable to check availability. Retry before confirming.', retry: 'Check again',
    invalidDuration: 'Enter a valid duration and time that finish by midnight.',
    bookingNotes: 'Booking notes / special requests',

    bookingSource: 'Booking source',
    openingHours: 'Opening hours', latestStart: 'Latest start',
    outsideHours: 'Choose a time within the shop’s opening hours that allows the game to finish before closing.',
    automaticDiscount: 'Automatic group discount',
    groupDiscountHelp: 'Group savings update automatically when the player count changes. Choose the birthday offer when applicable. Offers are not combined.',
    overrideTotal: 'Override total',
    finalTotal: 'Final total (VND)',
    overrideReason: 'Reason for price override',
    overrideHelp: 'The reason is required and saved with this booking.',
    invalidOverride: 'Enter a whole VND total of zero or more and a reason for the override.',
    sources: { walk_in: 'Walk-in', zalo: 'Zalo', whatsapp: 'WhatsApp', phone: 'Phone', website: 'Website', other: 'Other' },
    removeSplit: 'Remove payment split',
    bookingType: 'Booking type', customerBooking: 'Client booking', shop: 'Shop',
    searchCustomer: 'Search by name, phone or email, or enter a new client',
    createProfile: 'Create profile for “{name}”',
    createWithBooking: 'New client? Enter their name and optional contact details. The profile is saved when you confirm this booking.',
    profileSelected: 'Existing profile selected. Contact details below apply to this booking.',
    invalidBooking: 'Enter a valid date, time and player count (1–16).',
    invalidEmail: 'Enter a valid email address or leave it empty.',
    discountChanged: 'This discount no longer applies. Choose an available discount or no discount.',
    discountsHelp: '{count} offers match this game, date, time and player count. Customer usage limits are checked when confirming.',
    discountValue: 'Unique discount value', noGames: 'No games available at this shop',
    durationHelp: 'The full reserved time shown below blocks the arena. Availability is checked again when you confirm.',
  },
  vi: {
    noGame: 'Không chọn', startTime: 'Giờ bắt đầu', arenaCount: 'Số khu chơi',
    totalVatIncluded: 'Tổng tiền (đã gồm VAT)', totalBeforeVat: 'Tổng tiền trước VAT',
    vatNotes: 'Thông tin xuất hóa đơn VAT:\nTên công ty:\nĐịa chỉ công ty:\nMã số thuế công ty:',
    standardBooking: 'Trò chơi thông thường', eventBooking: 'Sự kiện / doanh nghiệp',
    reservedMinutes: 'Thời gian đặt (phút)', endTime: 'Giờ kết thúc', reservedTime: 'Tổng thời gian giữ chỗ',
    allowOutsideHours: 'Cho phép đặt ngoài giờ mở cửa',
    eventHelp: 'Nhập toàn bộ thời gian cần thiết, gồm chuẩn bị và thu dọn. Có thể nhập số phút bất kỳ, kết thúc trước hoặc đúng nửa đêm. Dùng Điều chỉnh tổng tiền cho giá sự kiện đã thỏa thuận.',
    contactName: 'Người liên hệ', contactHelp: 'Nhập tên công ty hoặc khách hàng ở trên và người liên hệ tại đây. Số điện thoại và email bên dưới dùng để liên hệ về đặt chỗ.',
    checkingAvailability: 'Đang kiểm tra lịch trống…', available: 'Khu chơi còn trống trong toàn bộ thời gian đặt.',
    unavailable: 'Khu chơi hoặc thời gian này không còn trống. Chọn khu chơi hoặc giờ khác.',
    availabilityError: 'Không thể kiểm tra lịch trống. Vui lòng thử lại trước khi xác nhận.', retry: 'Kiểm tra lại',
    invalidDuration: 'Nhập thời lượng và giờ hợp lệ, kết thúc trước hoặc đúng nửa đêm.',
    bookingNotes: 'Ghi chú đặt chỗ / yêu cầu đặc biệt',

    bookingSource: 'Nguồn đặt chỗ',
    openingHours: 'Giờ mở cửa', latestStart: 'Giờ bắt đầu muộn nhất',
    outsideHours: 'Chọn giờ trong thời gian mở cửa và đủ để hoàn thành trò chơi trước khi đóng cửa.',
    automaticDiscount: 'Tự động giảm giá nhóm',
    groupDiscountHelp: 'Ưu đãi nhóm tự động cập nhật khi thay đổi số người. Chọn ưu đãi sinh nhật khi phù hợp. Không cộng dồn ưu đãi.',
    overrideTotal: 'Điều chỉnh tổng tiền',
    finalTotal: 'Tổng tiền cuối cùng (VND)',
    overrideReason: 'Lý do điều chỉnh giá',
    overrideHelp: 'Bắt buộc nhập lý do. Lý do được lưu cùng đặt chỗ.',
    invalidOverride: 'Nhập tổng tiền VND nguyên không âm và lý do điều chỉnh.',
    sources: { walk_in: 'Khách đến trực tiếp', zalo: 'Zalo', whatsapp: 'WhatsApp', phone: 'Điện thoại', website: 'Website', other: 'Khác' },
    removeSplit: 'Xóa phần thanh toán',
    bookingType: 'Loại đặt chỗ', customerBooking: 'Đặt chỗ theo hồ sơ khách', shop: 'Cửa hàng',
    searchCustomer: 'Tìm theo tên, điện thoại, email hoặc nhập tên khách mới',
    createProfile: 'Tạo hồ sơ cho “{name}”',
    createWithBooking: 'Khách mới? Nhập tên và thông tin liên hệ nếu có. Hồ sơ được lưu khi xác nhận đặt chỗ này.',
    profileSelected: 'Đã chọn hồ sơ có sẵn. Thông tin liên hệ bên dưới áp dụng cho lượt đặt chỗ này.',
    invalidBooking: 'Nhập ngày, giờ và số người chơi hợp lệ (1–16).',
    invalidEmail: 'Nhập email hợp lệ hoặc để trống.',
    discountChanged: 'Ưu đãi này không còn áp dụng. Chọn ưu đãi khác hoặc không giảm giá.',
    discountsHelp: '{count} ưu đãi phù hợp với trò chơi, ngày, giờ và số người. Giới hạn sử dụng theo khách được kiểm tra khi xác nhận.',
    discountValue: 'Giá trị giảm giá riêng', noGames: 'Cửa hàng chưa có trò chơi khả dụng',
    durationHelp: 'Khu chơi được giữ trong toàn bộ thời gian bên dưới. Lịch trống được kiểm tra lại khi xác nhận.',
  },
} as const
