import type { StaffConsoleLanguage, StaffTab, StaffTabGroupId, StaffCommerceTab, StaffAttendanceTab, StaffHrTab, StaffScheduleScope, StaffRole, StaffRoleSort, StaffReportChartMode, StaffReportRangePreset, StaffShiftTemplateId, StaffEmploymentType, StaffPaymentMethod, StaffDiscountDayScope, StaffDiscountTicketType, StaffAudience, StaffGame, StaffPriceRule, StaffDiscount, StaffLoyaltyRule, StaffShiftStatus, StaffAttendanceStatus, StaffLeaveType, StaffLeaveStatus, StaffGender, StaffContractStatus, StaffHrSetupOptionType, StaffHrAdjustmentType, StaffHrAdjustmentStatus, StaffPayrollStatus, StaffPayrollPayCycle, StaffOrder } from './types'

export const staffConsoleText = {
  en: {
    accessRequired: 'Staff access required.',
    operationsMoney: {
      title: 'Booking & payments', bookingValue: 'Confirmed booking value', orderTotal: 'Recorded orders',
      orderPaid: 'Order payments', orderBalance: 'Order balance due', pendingValue: 'Pending requests / drafts',
      unlinkedValue: 'Bookings needing an order', needsOrder: 'Order reconciliation needed',
      pending: 'Awaiting confirmation', clear: 'No unlinked confirmed tickets',
      hint: 'Booking value includes confirmed tickets without an order. Payments and balance due cover recorded orders only. Pending requests are excluded from confirmed value. Reconcile unlinked tickets before collecting payment.',
      past: 'Totals cover the past sessions shown and their linked orders.',
    },
    active: 'active',
    inactive: 'inactive',
    allGames: 'All games',
    allPriceRules: 'All price rules',
    allRoles: 'All roles',
    any: 'any',
    chooseDate: 'Choose date',
    chooseTime: 'Choose time',
    closeRoleHelp: 'Close role explanation',
    compareOff: 'Turn on compare',
    compareWith: 'Compare with',
    customerFallback: 'Customer',
    defaultWalkInRate: 'Default walk-in rate',
    editDiscount: 'Edit discount',
    editGame: 'Edit game',
    editLoyaltyRule: 'Edit loyalty rule',
    editPriceRule: 'Edit price rule',
    editVoucher: 'Edit voucher',
    gameFallback: 'Game',
    gamePhotoHelp: 'JPG, PNG, or WEBP · max 2 MB · square photo works best.',
    loading: 'Loading Staff Console...',
    noContact: 'No contact',
    noData: 'No data',
    noDiscount: 'No discount',
    noUniqueDiscount: 'No unique discount',
    days: 'days',
    emailOverrideKeepsAdmin: 'Email override keeps this account in its protected role.',
    sharedKioskRoleProtected: 'Shared store account. Employee PIN access stays enabled for this account only.',
    noExpiry: 'no expiry',
    noneYet: 'None yet',
    newValue: 'New',
    noUsersFound: 'No users found.',
    reportTitleFallback: 'VRena report',
    split: 'Split',
    title: 'Staff Console',
    unknown: 'Unknown',
    unpaid: 'Unpaid',
    vndAmount: 'VND amount',
    walkIn: 'Walk-in / manual customer',
    actions: {
      addSplit: 'Add split',
      apply: 'Apply',
      calendar: 'Calendar',
      approve: 'Approve',
      confirmBooking: 'Confirm booking',
      complete: 'Complete',
      copyPreviousWeek: 'Copy previous week',
      done: 'Done',
      edit: 'Edit',
      editStats: 'Edit stats',
      excel: 'Excel',
      newGame: 'New game',
      nextWeek: 'Next week',
      noShow: 'No-show',
      paid: 'Paid',
      past: 'Past',
      pdf: 'PDF',
      previousWeek: 'Previous week',
      publish: 'Publish',
      publishWeek: 'Publish week',
      reject: 'Reject',
      remove: 'Remove',
      removePlayer: 'Remove player',
      restore: 'Restore',
      save: 'Save',
      saveParticipant: 'Save player',
      cancel: 'Cancel',
      cancelShift: 'Cancel shift',
      confirmDeleteAccount: 'Delete account',
      deleteAccount: 'Delete account',
      deleteSession: 'Delete',
      confirmDeleteSession: 'Delete',
      download: 'Download',
      preparingDownload: 'Preparing...',
      approvePayroll: 'Approve payroll',
      createEmployee: 'Create employee',
      downloadPayrollExcel: 'Download payroll Excel',
      generatePayroll: 'Generate payroll',
      saveAttendance: 'Save attendance',
      saveAdjustment: 'Save adjustment',
      saveDiscount: 'Save discount',
      saveEmployeeProfile: 'Save employee profile',
      saveGame: 'Save game',
      saveHrSettings: 'Save HR settings',
      saveLoyaltyRule: 'Save loyalty rule',
      savePrice: 'Save price',
      saveRole: 'Save role',
      saveRules: 'Save rules',
      saveShift: 'Save shift',
      saveSetupOption: 'Save option',
      saveVoucher: 'Save voucher',
      createPhoneAccount: 'Create phone account',
      copyTemporaryPassword: 'Copy temporary password',
      sendPasswordRequest: 'Send setup email',
      sessionCalendar: 'Session Calendar',
      submitLeave: 'Submit leave',
      today: 'Today',
      uploadCv: 'Upload CV',
      uploadPhoto: 'Upload photo',
      viewPayslip: 'View payslip',
      yesterday: 'Yesterday',
      previousPeriod: 'Previous period',
    },
    aria: {
      bookingDate: 'Booking date',
      bookingTime: 'Booking time',
      attendanceDate: 'Attendance date',
      closeReportCalendar: 'Close report calendar',
      clockIn: 'Clock-in time',
      clockOut: 'Clock-out time',
      leaveEnd: 'Leave end date',
      leaveStart: 'Leave start date',
      nightEnd: 'Night window end',
      nightStart: 'Night window start',
      openBookingCalendar: 'Open booking calendar',
      openSessionCalendar: 'Open session calendar',
      compareEndDate: 'Compare end date',
      compareStartDate: 'Compare start date',
      discountValueUnit: 'Discount value unit',
      discountStartTime: 'Discount start time',
      discountEndTime: 'Discount end time',
      discountValidFrom: 'Discount valid from',
      discountValidUntil: 'Discount valid until',
      draftShift: 'Draft shift',
      graphDisplay: 'Graph display',
      loyaltyValidFrom: 'Loyalty valid from',
      loyaltyValidUntil: 'Loyalty valid until',
      nextReportMonth: 'Next report month',
      paymentAmount: 'Payment amount',
      paymentMethod: 'Payment method',
      paymentMix: 'Payment mix',
      periodComparison: 'Period comparison',
      previousReportMonth: 'Previous report month',
      priceEndTime: 'Price end time',
      priceStartTime: 'Price start time',
      priceValidFrom: 'Price valid from',
      priceValidUntil: 'Price valid until',
      reportEndDate: 'Report end date',
      reportStartDate: 'Report start date',
      revenueByDayOfWeek: 'Revenue by day of week',
      revenueByHour: 'Revenue by hour',
      salesByDay: 'Sales by day',
      staffConsole: 'Staff Console',
    },
    chartModes: {
      cheese: 'Cheese',
      columns: 'Column',
      curves: 'Curves',
    } satisfies Record<StaffReportChartMode, string>,
    commerceTabs: {
      discounts: 'Discounts',
      vouchers: 'Vouchers',
      loyalty: 'Loyalty Points',
    } satisfies Record<StaffCommerceTab, string>,
    attendanceTabs: {
      schedule: 'Schedule',
      clock: 'Clock-in log',
      timesheet: 'Timesheet',
      leave: 'Leave',
      settings: 'Rules',
    } satisfies Record<StaffAttendanceTab, string>,
    hrTabs: {
      employees: 'Employee profile',
      schedule: 'Calendar',
      timesheet: 'Timesheet',
      payroll: 'Payroll',
      adjustments: 'Bonuses',
      advances: 'Debts & advances',
      zalo: 'Zalo Mini App',
      settings: 'HR settings',
    } satisfies Record<StaffHrTab, string>,
    shiftStatuses: {
      cancelled: 'cancelled',
      completed: 'completed',
      draft: 'draft',
      published: 'published',
    } satisfies Record<StaffShiftStatus, string>,
    shiftTemplates: {
      afternoon: 'Afternoon',
      evening: 'Evening',
      full_day: 'Full day',
      opening: 'Opening',
    } satisfies Record<StaffShiftTemplateId, string>,
    scheduleScopes: {
      all: 'All departments',
      department: 'My department',
      mine: 'My shifts',
    } satisfies Record<StaffScheduleScope, string>,
    attendanceStatuses: {
      absent: 'absent',
      holiday: 'holiday',
      late: 'late',
      leave: 'leave',
      no_show: 'no-show',
      present: 'present',
    } satisfies Record<StaffAttendanceStatus, string>,
    leaveTypes: {
      annual: 'annual leave',
      personal: 'personal leave',
      public_holiday: 'public holiday',
      sick: 'sick leave',
      unpaid: 'unpaid leave',
    } satisfies Record<StaffLeaveType, string>,
    leaveStatuses: {
      approved: 'approved',
      cancelled: 'cancelled',
      rejected: 'rejected',
      requested: 'requested',
    } satisfies Record<StaffLeaveStatus, string>,
    employmentTypes: {
      full_time: 'Full-time',
      part_time: 'Part-time',
      contractor: 'Contractor',
      intern: 'Intern',
      probation: 'Probation',
      probation_full_time: 'Probation full-time',
      probation_part_time: 'Probation part-time',
    } satisfies Record<StaffEmploymentType, string>,
    genderOptions: {
      female: 'Female',
      male: 'Male',
      non_binary: 'Non-binary',
      prefer_not_to_say: 'Prefer not to say',
      other: 'Other',
    } satisfies Record<StaffGender, string>,
    contractStatuses: {
      active: 'Active',
      probation: 'Probation',
      suspended: 'Suspended',
      ended: 'Ended',
      draft: 'Draft',
    } satisfies Record<StaffContractStatus, string>,
    adjustmentTypes: {
      bonus: 'Bonus',
      commission: 'Commission',
      allowance: 'Allowance',
      lunch_allowance: 'Lunch allowance',
      deduction: 'Deduction',
      advance: 'Advance',
      debt: 'Debt',
      debt_repayment: 'Debt repayment',
    } satisfies Record<StaffHrAdjustmentType, string>,
    adjustmentStatuses: {
      draft: 'draft',
      pending: 'pending validation',
      approved: 'approved',
      rejected: 'rejected',
      paid: 'paid',
      cancelled: 'cancelled',
    } satisfies Record<StaffHrAdjustmentStatus, string>,
    payrollStatuses: {
      draft: 'draft',
      pending: 'pending',
      approved: 'approved',
      paid: 'paid',
      cancelled: 'cancelled',
    } satisfies Record<StaffPayrollStatus, string>,
    payrollPayCycles: {
      monthly: 'Monthly',
      semi_monthly: 'Semi-monthly',
      weekly: 'Weekly',
      custom: 'Custom',
    } satisfies Record<StaffPayrollPayCycle, string>,
    hrSetupOptionTypes: {
      department: 'Department',
      job_title: 'Job title',
      location: 'Location',
      contract_status: 'Contract status',
      contract_type: 'Contract type',
      employment_type: 'Employment type',
      payroll_template: 'Payroll template',
      allowance: 'Allowance category',
      deduction: 'Deduction category',
    } satisfies Record<StaffHrSetupOptionType, string>,
    dayTypes: {
      custom: 'custom',
      holiday: 'holiday',
      weekday: 'weekday',
      weekend: 'weekend',
    } satisfies Record<StaffPriceRule['day_type'], string>,
    discountDayScopes: {
      all: 'All days',
      fri: 'Friday',
      mon: 'Monday',
      sat: 'Saturday',
      sun: 'Sunday',
      thu: 'Thursday',
      tue: 'Tuesday',
      wed: 'Wednesday',
      weekday: 'Weekdays',
      weekend: 'Weekend',
    } satisfies Record<StaffDiscountDayScope, string>,
    discountTicketTypes: {
      all: 'All ticket types',
      birthday: 'Birthday / Events',
      corporate: 'Corporate',
      individual: 'Individual',
    } satisfies Record<StaffDiscountTicketType, string>,
    discountTypes: {
      birthday: 'birthday',
      fixed_amount: 'fixed amount',
      free_ticket: 'free ticket',
      group: 'group',
      percentage: 'percentage',
      resident: 'resident',
    } satisfies Record<StaffDiscount['discount_type'], string>,
    gameTypes: {
      escape: 'escape',
      other: 'other',
      shooting: 'shooting',
      tournament: 'tournament',
    } satisfies Record<StaffGame['game_type'], string>,
    ticketTypes: {
      birthday: 'Birthday',
      corporate: 'Corporate',
      individual: 'Individual',
    } satisfies Record<string, string>,
    audienceOptions: {
      family_friendly: 'Family friendly',
      scary: 'Scary',
      fun: 'Fun',
      quest: 'Quest',
      teamwork: 'Teamwork',
      beginner_friendly: 'Beginner friendly',
      competitive: 'Competitive',
    } satisfies Record<StaffAudience, string>,
    labels: {
      actions: 'Actions',
      active: 'Active',
      activeEmployee: 'Active employee',
      inactiveEmployee: 'Inactive employee',
      accountantExports: 'Accountant exports',
      arena: 'Arena',
      arenaIds: 'Arena IDs',
      attachmentList: 'Attachment list',
      annualLeaveDays: 'Annual leave days',
      attendance: 'Attendance',
      attendanceDate: 'Attendance date',
      attendanceSchedule: 'Attendance & work schedule',
      bankAccount: 'Bank account',
      bankName: 'Bank name',
      bankTransfer: 'Bank transfer',
      baseSalary: 'Base salary (đ)',
      bestSellingGame: 'Best-selling game',
      bookings: 'Bookings',
      breakMinutes: 'Break minutes',
      calculation: 'Calculation',
      cancelled: 'Cancelled',
      cash: 'Cash',
      capacity: 'Capacity',
      checkIns: 'Check-ins',
      codeOptional: 'Code (optional)',
      banAccount: 'Ban this account too',
      compare: 'Compare',
      compareEditingHint: 'Calendar clicks now edit the compare range.',
      compareInactiveHint: 'Switch to Compare above to edit this range.',
      compareRange: 'Compare range',
      confirmDeleteWord: 'Type DELETE to confirm',
      createCustomerAccount: 'Create customer account',
      awardAchievement: 'Unlock achievement',
      awardAchievementHelp: 'Manually unlock an existing player achievement when the automatic session data does not cover the real-world moment.',
      awardNote: 'Staff note',
      awardToPlayer: 'Why are you unlocking it?',
      chooseAchievement: 'Choose achievement',
      choosePlayer: 'Choose player',
      grantedAwards: 'Manual unlocks',
      createDiscount: 'Create discount',
      createGame: 'Create game',
      createLoyaltyRule: 'Create loyalty rule',
      createPriceRule: 'Create price rule',
      createVoucher: 'Create voucher',
      current: 'current',
      communitySession: 'Community session',
      customer: 'Customer',
      guestBooking: 'Guest booking',
      customerAccountHelp: 'Names may repeat. Every new player needs a unique nickname. Leave email blank to create a phone account with a temporary first-login password.',
      customerAccountPhonePasswordHelp: 'No email: VRena generates a temporary password. The customer signs in, adds and verifies an email, then creates a private permanent password.',
      customerTemporaryPassword: 'Temporary first-login password',
      customerTemporaryPasswordHelp: 'Show this once to the customer. It expires after 24 hours. Staff cannot retrieve it later.',
      customerName: 'Customer name',
      customerProfile: 'Customer profile',
      noAwardsYet: 'No manual unlocks yet.',
      noPlayersFound: 'No matching players.',
      optional: 'optional',
      password: 'Password',
      confirmPassword: 'Confirm password',
      sendAward: 'Unlock achievement',
      date: 'Date',
      dateRange: 'Date range',
      dayType: 'Day type',
      deleteReason: 'Reason',
      description: 'Description',
      audience: 'Audience',
      discount: 'Discount',
      discountRuleHelp: 'Discounts apply automatically when their rules match. Vouchers work when the customer enters the voucher code.',
      discountConditions: 'Conditions',
      discountType: 'Discount type',
      discountVoucher: 'Discount / voucher',
      discounts: 'Discounts',
      duration: 'Duration',
      escapeChapters: 'Escape chapters',
      email: 'E-mail',
      employeeCode: 'Employee code',
      attendanceNumber: 'Attendance number',
      employmentType: 'Employment type',
      end: 'End',
      endDate: 'End date',
      contractStatus: 'Contract status',
      contractType: 'Contract type',
      contractStartDate: 'Contract start date',
      contractEndDate: 'Contract end date',
      editingRange: 'Editing',
      emergencyContact: 'Emergency contact',
      estimatedPayroll: 'Estimated payroll',
      exportFormat: 'Format',
      exportLanguage: 'Language',
      exportReport: 'Report',
      exportStore: 'Store / location',
      holidayHours: 'Holiday hours',
      hours: 'Hours',
      hourlyRate: 'Gross hourly rate (đ)',
      monthlyGross: 'Monthly gross (đ)',
      missingDocuments: 'Missing documents',
      filterByRole: 'Filter by role',
      game: 'Game',
      guideGameplay: 'GamePlay',
      guideLanguage: 'Guide language',
      guideSummary: 'Guide summary',
      guideTips: 'Guide tips',
      gamePhoto: 'Game photo',
      games: 'Games',
      imageUrl: 'Image URL',
      includeAttachments: 'Include attachments list',
      internalNote: 'Internal note',
      jobTitle: 'Job title',
      department: 'Department',
      lateNoShow: 'Late / no-show',
      legalName: 'Legal name',
      leaveHours: 'Leave hours',
      leaveBalance: 'Available leave',
      leaveType: 'Leave type',
      location: 'Location',
      mainWorkLocation: 'Main workplace',
      payrollLocation: 'Payroll outlet',
      managerNote: 'Manager note',
      maxPlayersArena: 'Max players / arena',
      maxPlayers: 'Max players',
      maxDiscountAmount: 'Max discount amount',
      maxUses: 'Max uses',
      limitByHour: 'Limit by hour',
      minPlayers: 'Min players',
      minimumSpend: 'Minimum spend',
      name: 'Name',
      newBooking: 'New booking',
      nickname: 'Nickname',
      noLinkedOrder: 'No linked order',
      no: 'No',
      noShows: 'No-shows',
      nightHours: 'Night hours',
      nightWindow: 'Night window',
      notes: 'Notes',
      order: 'Order',
      orderStatus: 'Order status',
      orders: 'Orders',
      off: 'Off',
      operationsCalendar: 'Operations calendar',
      operationsDate: 'Operations date',
      paid: 'Paid',
      payment: 'Payment',
      paymentSplits: 'Payment splits',
      paymentStatus: 'Payment status',
      paymentMix: 'Payment mix',
      payrollLink: 'Attendance / payroll link',
      payrollNote: 'Payroll note',
      payrollRun: 'Payroll run',
      payrollCode: 'Payroll code',
      payrollName: 'Payroll name',
      payCycle: 'Pay cycle',
      payslipPreview: 'Vietnam payslip preview',
      periodStart: 'Period start',
      periodEnd: 'Period end',
      perCustomerLimit: 'Per customer limit',
      perVndSpent: 'Per VND spent',
      phone: 'Phone',
      personalEmail: 'Personal e-mail',
      personalPhone: 'Personal phone',
      profilePhoto: 'Profile photo',
      cvDocument: 'CV document',
      profileCompletion: 'Profile completion',
      players: 'Players',
      addPlayer: 'Add player',
      sessionFields: 'Session fields',
      participantResults: 'Player results',
      chapterTimes: 'Chapter times',
      chapter: 'Chapter',
      score: 'Score',
      place: 'Place',
      accuracy: 'Accuracy',
      projectiles: 'Hits',
      movement: 'Movement',
      escapeTime: 'Escape time',
      loyaltyPoints: 'Loyalty points',
      pointsEarned: 'Points earned',
      pointsExpireAfterDays: 'Points expire after days',
      redeemValue: 'Redeem value',
      privateSession: 'Private session',
      priceArenaSlot: 'Price / arena slot (đ)',
      pricePlayer: 'Price / player (đ)',
      priceRule: 'Price rule',
      priceRules: 'Price rules',
      privateEmployeeProfile: 'Private employee profile',
      address: 'Address',
      dateOfBirth: 'Date of birth',
      gender: 'Gender',
      nationalId: 'National ID',
      regularHours: 'Regular hours',
      remaining: 'Remaining',
      restoreDeletedRecords: 'Restore deleted records',
      deletedBy: 'Deleted by',
      referenceRange: 'Reference range',
      reportRange: 'Report range',
      roleExplanation: 'Role explanation',
      roleFor: 'Role for',
      roles: 'Roles',
      rounds: 'Rounds',
      rule: 'Rule',
      ruleName: 'Rule name',
      sales: 'Sales',
      salesTrend: 'Sales trend',
      revenueByDayOfWeek: 'Revenue by day of week',
      revenueByHour: 'Revenue by hour',
      searchUsers: 'Search users',
      selectedRange: 'Selected range',
      sessions: 'Sessions',
      scheduledHours: 'Scheduled hours',
      shiftDate: 'Shift date',
      shiftList: 'Shift list',
      shiftRole: 'Shift role',
      scheduleScope: 'Schedule view',
      shiftTemplate: 'Shift template',
      sortBy: 'Sort by',
      slug: 'Slug',
      standardDay: 'Standard day length',
      standardDayHelp: 'Use HH:mm. Example: 07:15 = 7h 15m.',
      standardDayPresets: 'Standard day presets',
      standardBreakMinutes: 'Standard break (minutes)',
      standardShiftTemplates: 'Standard shifts',
      standardWeek: 'Standard week',
      start: 'Start',
      startDate: 'Start date',
      status: 'Status',
      staffMember: 'Staff member',
      socialInsurance: 'Social insurance number',
      standardMonthlyDays: 'Standard monthly days',
      standardMonthlyHours: 'Standard monthly hours',
      subtotal: 'Subtotal',
      summary: 'Summary',
      taxCodeEmployee: 'Tax code',
      time: 'Time',
      ticketBookings: 'Ticket bookings',
      ticketType: 'Ticket type',
      total: 'Total',
      totalCompanyCost: 'Total company cost',
      totalGross: 'Total gross',
      totalNet: 'Total net',
      totalPaid: 'Total paid',
      totalSales: 'Total sales',
      type: 'Type',
      uniqueDiscount: 'Unique discount',
      used: 'used',
      value: 'Value',
      validFrom: 'Valid from',
      validUntil: 'Valid until',
      validUntilHelp: 'optional, by default forever',
      voucherCodeRequired: 'Voucher code *',
      vouchers: 'Vouchers',
      weeklyRange: 'Week',
      weeklySchedule: 'Weekly schedule',
      allDays: 'All days',
      allTicketTypes: 'All ticket types',
      overtimeHours: 'Overtime hours',
      overtimePay: 'Overtime pay',
      paidLeave: 'Paid leave',
      overtimeMonthlyCap: 'Monthly overtime cap',
      overtimeYearlyCap: 'Yearly overtime cap',
      normalOvertimeMultiplier: 'Normal OT multiplier',
      nightOvertimeMultiplier: 'Night OT multiplier',
      holidayOvertimeMultiplier: 'Holiday OT multiplier',
      lunchAllowance: 'Lunch allowance / day',
      mealAllowance: 'Meal allowance',
      restPeriodHours: 'Minimum rest (hours)',
      restWarnings: 'Rest alerts',
      employeeContributionRate: 'Employee contribution %',
      employerContributionRate: 'Employer contribution %',
      pitWithholdingRate: 'PIT withholding %',
      dependentsCount: 'Dependents',
      grossIncome: 'Gross income',
      netIncome: 'Net income',
      companyCost: 'Company cost',
      allowances: 'Allowances',
      bonuses: 'Bonuses',
      advances: 'Advances',
      deductions: 'Deductions',
      employeeContributions: 'Employee contributions',
      employerContributions: 'Employer contributions',
      pitWithheld: 'PIT withheld',
      outstandingDebt: 'Outstanding debt',
      workedHours: 'Worked hours',
      yes: 'Yes',
    },
    loyaltyCalculation: {
      per_booking: 'Per booking',
      per_player: 'Per player',
      per_visit: 'Per visit/check-in',
      per_vnd_spent: 'Spend based',
    } satisfies Record<StaffLoyaltyRule['calculation_type'], string>,
    messages: {
      clickUploadGamePhoto: 'Click to upload game photo',
      accountDeleteBanNote: 'Ban metadata stays attached to the deleted profile for future review.',
      accountDeleteBody: 'This soft-deletes the user profile and removes it from active app lists. Historical sessions, scores, orders, and audit records stay intact.',
      accountDeleteTitle: 'Delete account?',
      operationDeleteBody: 'This removes it from the Sessions and Tickets lists. Linked players are removed and any linked order is marked cancelled.',
      operationDeleteTitle: 'Delete this session or ticket?',
      accountDeleted: 'Account deleted.',
      accountDeleting: 'Deleting account...',
      accountDeleteConfirmationHelp: 'Write DELETE exactly to unlock this action.',
      accountantExportHelp: 'Choose filters, report type, and format, then download.',
      accountantExportSourcePending: 'Detailed source table is not configured yet. This export includes the available report summary for the selected range.',
      accountantAttachmentsExcelOnly: 'Attachment lists are available in Excel files.',
      reportDownloadFailed: 'The report could not be downloaded. Please try again.',
      reportDownloadStarted: 'Download started.',
      attendanceIntro: 'Plan shifts, clock-ins, leave, overtime, and Vietnam labor-rule checks in one place.',
      attendanceReadOnly: 'Read-only view. Viewer can inspect attendance, but cannot save changes.',
      attendanceRulesSaved: 'Attendance rules saved.',
      attendanceSaved: 'Attendance saved.',
      customerAccountEmailRequired: 'Enter a customer email.',
      customerAccountInvited: 'Customer account created. Password request sent.',
      customerAccountNameRequired: 'Enter the customer name.',
      customerAccountNicknameRequired: 'Enter a customer nickname.',
      customerAccountNicknameTaken: 'This nickname is already in use.',
      customerAccountPasswordMismatch: 'Passwords do not match.',
      customerAccountPasswordRequired: 'Enter a password of at least 6 characters.',
      customerAccountPhoneCreated: 'Phone account created. Give the temporary password below to the customer.',
      customerTemporaryPasswordCopied: 'Temporary password copied.',
      customerAccountPhoneRequired: 'Enter a valid customer phone number.',
      guestBookingHelp: 'No customer profile, name, contact details, or player stats will be created. Payment, player count, date, time, duration, and game are still recorded.',
      achievementAwarded: 'Achievement unlocked for this player.',
      achievementAlreadyAwarded: 'Already awarded to this player.',
      achievementAwardSelectPlayer: 'Choose a player first.',
      discountSaved: 'Discount saved.',
      draftShiftCreated: 'Draft shift created.',
      draftShiftExists: 'That draft already exists for this staff member and day.',
      employeeProfileIntro: 'Private HR details linked to attendance and payroll. Visible to staff HR roles only.',
      employeeProfileSaved: 'Employee profile saved.',
      hrIntro: 'Company HR hub for employee records, schedule health, payroll, payslips, bonuses, advances, and setup.',
      hrSetupUnavailable: 'Apply the HR migration to enable saved HR settings, bonuses, payroll runs, and document uploads.',
      hrSettingsSaved: 'HR settings saved.',
      hrSetupOptionSaved: 'HR option saved.',
      adjustmentSaved: 'HR adjustment saved.',
      adjustmentApproved: 'Adjustment approved.',
      payrollGenerated: 'Payroll draft generated.',
      payrollApproved: 'Payroll approved.',
      profilePhotoHelp: 'JPG, PNG, or WEBP · max 2 MB.',
      cvHelp: 'PDF, DOC, or DOCX · max 10 MB.',
      profilePhotoTooLarge: 'Profile photo must be 2 MB or smaller.',
      cvTooLarge: 'CV must be 10 MB or smaller.',
      documentUploaded: 'Document uploaded.',
      documentUploadFailed: 'Document upload failed.',
      noAdjustments: 'No HR adjustments for this period.',
      noPayrollRuns: 'No payroll runs yet.',
      noHrDocuments: 'No HR documents uploaded yet.',
      noScheduleShifts: 'No scheduled shifts for this period.',
      inactiveEmployeePlanningBlocked: 'Inactive employee: reactivate this employee profile before planning new shifts.',
      gamePhotoSmall: 'Game photo must be 2 MB or smaller.',
      gamePhotoType: 'Game photo must be JPG, PNG, or WEBP.',
      gamePhotoUploaded: 'Game photo uploaded. Save the game to keep it.',
      gameGuideHelp: 'Select a language, then edit the summary, GamePlay, and tips for this game only. Use one line per GamePlay item or tip.',
      gameSaved: 'Game saved.',
      loyaltyIntro: 'Define how customers earn points. Redemption will use these rules later.',
      loyaltyRuleSaved: 'Loyalty rule saved.',
      loyaltySingleActiveConfirm: 'Only one loyalty rule can be active. Saving this rule will deactivate {rule} but keep it for analytics. Continue?',
      loyaltyPointsUpdated: 'Loyalty points updated.',
      loyaltyPointsUpdating: 'Updating loyalty points...',
      leaveSaved: 'Leave request saved.',
      leaveUpdated: 'Leave request updated.',
      noAttendanceLogs: 'No clock-in logs for this week.',
      noDiscounts: 'No discounts yet.',
      noLeaveRequests: 'No leave requests for this week.',
      noLoyaltyRules: 'No loyalty rules yet.',
      noOrders: 'No orders in this range.',
      noSales: 'No sales in this period yet.',
      noShifts: 'No shifts for this week.',
      noStaffProfiles: 'No staff profiles yet.',
      noSoftDeleted: 'No soft-deleted records.',
      noVouchers: 'No vouchers yet.',
      orderConfirmed: 'Order {order} confirmed · {total}',
      orderCreating: 'Creating order...',
      orderEditInvalid: 'Choose a game, date, and time, then enter a whole VND total of zero or more.',
      orderUpdated: 'Order updated.',
      priceRuleSaved: 'Price rule saved.',
      readOnlyBooking: 'Read-only view. Viewer can inspect this flow, but cannot create bookings.',
      readOnlyCommerce: 'Read-only view. Viewer can inspect these rules, but cannot save changes.',
      readOnlyGames: 'Read-only view. Viewer can inspect games, but cannot save changes.',
      readOnlyPrices: 'Read-only view. Viewer can inspect price rules, but cannot save changes.',
      restoreIntro: 'Owner only. Restoring clears deleted_at, deleted_by, and delete_reason.',
      restoringRecord: 'Restoring record...',
      recordRestored: 'Record restored.',
      roleSaveFailed: 'Role was not saved. Apply the latest Supabase SQL migration, then try again.',
      roleSaveMismatch: 'Role was not saved. Supabase still returned a different role.',
      roleUpdated: 'Role updated.',
      roleUpdating: 'Updating role...',
      shiftSaved: 'Shift saved.',
      staffTooManyAttempts: 'Too many attempts. Please wait a moment and try again.',
      planningConflictDailyLimit: 'Above standard daily hours.',
      planningConflictLeave: 'Approved leave on this day.',
      planningConflictOverlap: 'Overlaps another shift.',
      planningGridHelp: 'Click a cell to draft a shift. Drag chips to move them.',
      previousWeekCopied: 'Previous week copied as draft shifts.',
      previousWeekEmpty: 'No shifts found in previous week.',
      previousWeekNoNew: 'Previous week already exists here. Nothing copied.',
      weekPublished: 'Week published.',
      uniqueDiscountHelp: 'One-off discount for this booking only. It does not create a reusable voucher.',
      uploadGamePhoto: 'Uploading game photo...',
      noOperationSessions: 'No sessions or ticket bookings for this day.',
      operationsIntro: 'Manage sessions, ticket bookings, capacity, payments, check-ins, players, and results in one place.',
      operationSessionSaved: 'Session updated.',
      operationParticipantSaved: 'Player updated.',
      operationParticipantAdded: 'Player added.',
      operationParticipantRemoved: 'Player removed.',
      operationSessionDeleted: 'Session deleted.',
      operationSessionDeleting: 'Deleting session...',
      voucherCodeRequired: 'Voucher code is required.',
      voucherSaved: 'Voucher saved.',
    },
    orderStatuses: {
      cancelled: 'cancelled',
      completed: 'completed',
      confirmed: 'confirmed',
      draft: 'draft',
      no_show: 'no_show',
      paid: 'paid',
      partially_paid: 'partially_paid',
      refunded: 'refunded',
    } satisfies Record<StaffOrder['order_status'], string>,
    paymentMethods: {
      bank_transfer: 'Bank Transfer',
      cash: 'Cash',
    } satisfies Record<StaffPaymentMethod, string>,
    roles: {
      admin: 'Admin',
      cashier: 'Office Staff',
      employee: 'Employee (PIN only)',
      manager: 'Manager',
      owner: 'Owner',
      player: 'Player',
      staff: 'Staff',
      viewer: 'Viewer',
    } satisfies Record<StaffRole, string>,
    roleSorts: {
      created_desc: 'Created last',
      email_asc: 'E-mail A-Z',
      name_asc: 'Name A-Z',
      name_desc: 'Name Z-A',
      role_asc: 'Role low-high',
      role_desc: 'Role high-low',
    } satisfies Record<StaffRoleSort, string>,
    reportRangePresets: {
      today: 'Sessions',
      yesterday: 'Yesterday',
      this_week: 'This week',
      last_week: 'Last week',
      this_month: 'This month',
      last_month: 'Last month',
      last_30: 'Last 30 days',
      last_60: 'Last 60 days',
      last_90: 'Last 90 days',
    } satisfies Record<StaffReportRangePreset, string>,
    reportWeekdays: ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'],
    roleHelp: [
      { title: 'Owner', body: 'Full Staff Console access, role management, restore tools, and every client app feature.' },
      { title: 'Admin', body: 'Full daily operations access and role management below Owner. Restore stays Owner only.' },
      { title: 'Office Staff', body: 'Viewer access plus editable reports and full Attendance edit access.' },
      { title: 'Viewer', body: 'Can use the normal player app, view the whole Staff Console, and adjust or download reports. All other staff data is read-only.' },
      { title: 'Employee (PIN only)', body: 'No personal web-app access. The employee enters their PIN on the shared store account and receives the Manager or Staff permissions configured in HR.' },
      { title: 'Player', body: 'Client app only. No Staff Console access.' },
    ],
    tabs: {
      clientProfile: 'Client Profile',
      discounts: 'Offers',
      attendance: 'Attendance',
      games: 'Games',
      hr: 'HR',
      new: 'New Booking',
      orders: 'Orders',
      prices: 'Prices',
      report: 'Report',
      restore: 'Restore',
      roles: 'Roles',
      today: 'Today',
    } satisfies Record<StaffTab, string>,
    tabGroups: {
      admin: 'Admin',
      operate: 'Operate',
      reports: 'Reports',
      setup: 'Setup',
      team: 'Team',
    } satisfies Record<StaffTabGroupId, string>,
  },
  vi: {
    operationsMoney: {
      title: 'Đặt chỗ & thanh toán', bookingValue: 'Giá trị đặt chỗ đã xác nhận', orderTotal: 'Đơn hàng đã ghi nhận',
      orderPaid: 'Thanh toán đơn hàng', orderBalance: 'Đơn hàng còn phải thu', pendingValue: 'Yêu cầu chờ / đơn nháp',
      unlinkedValue: 'Đặt chỗ cần tạo đơn', needsOrder: 'Cần đối soát đơn hàng',
      pending: 'Chờ xác nhận', clear: 'Không có vé đã xác nhận thiếu đơn hàng',
      hint: 'Giá trị đặt chỗ gồm cả vé đã xác nhận chưa có đơn hàng. Thanh toán và số còn phải thu chỉ tính đơn hàng đã ghi nhận. Yêu cầu đang chờ không thuộc giá trị đã xác nhận. Đối soát vé chưa có đơn trước khi thu tiền.',
      past: 'Tổng chỉ tính các phiên trước đây đang hiển thị và đơn hàng liên kết.',
    },
    accessRequired: 'Cần quyền nhân viên.',
    active: 'đang bật',
    inactive: 'đã tắt',
    allGames: 'Tất cả trò chơi',
    allPriceRules: 'Tất cả quy tắc giá',
    allRoles: 'Tất cả vai trò',
    any: 'bất kỳ',
    chooseDate: 'Chọn ngày',
    chooseTime: 'Chọn giờ',
    closeRoleHelp: 'Đóng giải thích vai trò',
    compareOff: 'Bật so sánh',
    compareWith: 'So sánh với',
    customerFallback: 'Khách hàng',
    defaultWalkInRate: 'Giá khách tại quầy',
    editDiscount: 'Sửa ưu đãi',
    editGame: 'Sửa trò chơi',
    editLoyaltyRule: 'Sửa quy tắc điểm',
    editPriceRule: 'Sửa quy tắc giá',
    editVoucher: 'Sửa voucher',
    gameFallback: 'Trò chơi',
    gamePhotoHelp: 'JPG, PNG hoặc WEBP · tối đa 2 MB · ảnh vuông hiển thị đẹp nhất.',
    loading: 'Đang tải Bảng nhân viên...',
    noContact: 'Chưa có liên hệ',
    noData: 'Chưa có dữ liệu',
    noDiscount: 'Không ưu đãi',
    noUniqueDiscount: 'Không có ưu đãi riêng',
    days: 'ngày',
    emailOverrideKeepsAdmin: 'Email cố định vẫn giữ tài khoản này trong vai trò được bảo vệ.',
    sharedKioskRoleProtected: 'Tài khoản dùng chung tại cửa hàng. Chỉ tài khoản này được giữ quyền truy cập bằng PIN nhân viên.',
    noExpiry: 'không hết hạn',
    noneYet: 'Chưa có',
    newValue: 'Mới',
    noUsersFound: 'Không tìm thấy người dùng.',
    reportTitleFallback: 'Báo cáo VRena',
    split: 'Tách thanh toán',
    title: 'Bảng nhân viên',
    unknown: 'Không rõ',
    unpaid: 'Chưa thanh toán',
    vndAmount: 'Số tiền VND',
    walkIn: 'Khách tại quầy / nhập tay',
    actions: {
      addSplit: 'Thêm phần thanh toán',
      apply: 'Áp dụng',
      calendar: 'Lịch',
      approve: 'Duyệt',
      confirmBooking: 'Xác nhận đặt chỗ',
      complete: 'Hoàn tất',
      copyPreviousWeek: 'Sao chép tuần trước',
      done: 'Hoàn tất',
      edit: 'Sửa',
      editStats: 'Chỉnh sửa thống kê',
      excel: 'Excel',
      newGame: 'Trò chơi mới',
      nextWeek: 'Tuần sau',
      noShow: 'Không đến',
      paid: 'Đã thanh toán',
      past: 'Đã qua',
      pdf: 'PDF',
      previousWeek: 'Tuần trước',
      publish: 'Công bố',
      publishWeek: 'Công bố tuần',
      reject: 'Từ chối',
      remove: 'Xóa',
      removePlayer: 'Xóa người chơi',
      restore: 'Khôi phục',
      save: 'Lưu',
      saveParticipant: 'Lưu người chơi',
      cancel: 'Hủy',
      cancelShift: 'Hủy ca',
      confirmDeleteAccount: 'Xóa tài khoản',
      deleteAccount: 'Xóa tài khoản',
      deleteSession: 'Xóa',
      confirmDeleteSession: 'Xóa',
      download: 'Tải xuống',
      preparingDownload: 'Đang chuẩn bị...',
      approvePayroll: 'Duyệt bảng lương',
      createEmployee: 'Tạo nhân viên',
      downloadPayrollExcel: 'Tải Excel bảng lương',
      generatePayroll: 'Tạo bảng lương',
      saveAttendance: 'Lưu chấm công',
      saveAdjustment: 'Lưu khoản điều chỉnh',
      saveDiscount: 'Lưu ưu đãi',
      saveEmployeeProfile: 'Lưu hồ sơ nhân viên',
      saveGame: 'Lưu trò chơi',
      saveHrSettings: 'Lưu thiết lập HR',
      saveLoyaltyRule: 'Lưu quy tắc điểm',
      savePrice: 'Lưu giá',
      saveRole: 'Lưu vai trò',
      saveRules: 'Lưu quy định',
      saveShift: 'Lưu ca',
      saveSetupOption: 'Lưu tùy chọn',
      saveVoucher: 'Lưu voucher',
      createPhoneAccount: 'Tạo tài khoản bằng số điện thoại',
      copyTemporaryPassword: 'Sao chép mật khẩu tạm thời',
      sendPasswordRequest: 'Gửi email tạo mật khẩu',
      sessionCalendar: 'Lịch phiên',
      submitLeave: 'Gửi nghỉ phép',
      today: 'Hôm nay',
      uploadCv: 'Tải CV',
      uploadPhoto: 'Tải ảnh',
      viewPayslip: 'Xem phiếu lương',
      yesterday: 'Hôm qua',
      previousPeriod: 'Kỳ trước',
    },
    aria: {
      bookingDate: 'Ngày đặt chỗ',
      bookingTime: 'Giờ đặt chỗ',
      attendanceDate: 'Ngày chấm công',
      closeReportCalendar: 'Đóng lịch báo cáo',
      clockIn: 'Giờ vào ca',
      clockOut: 'Giờ ra ca',
      leaveEnd: 'Ngày kết thúc nghỉ',
      leaveStart: 'Ngày bắt đầu nghỉ',
      nightEnd: 'Kết thúc giờ đêm',
      nightStart: 'Bắt đầu giờ đêm',
      openBookingCalendar: 'Mở lịch đặt chỗ',
      openSessionCalendar: 'Mở lịch phiên',
      compareEndDate: 'Ngày kết thúc so sánh',
      compareStartDate: 'Ngày bắt đầu so sánh',
      discountValueUnit: 'Đơn vị ưu đãi',
      discountStartTime: 'Giờ bắt đầu ưu đãi',
      discountEndTime: 'Giờ kết thúc ưu đãi',
      discountValidFrom: 'Ưu đãi hiệu lực từ',
      discountValidUntil: 'Ưu đãi hiệu lực đến',
      draftShift: 'Tạo ca nháp',
      graphDisplay: 'Cách hiển thị biểu đồ',
      loyaltyValidFrom: 'Điểm hiệu lực từ',
      loyaltyValidUntil: 'Điểm hiệu lực đến',
      nextReportMonth: 'Tháng báo cáo sau',
      paymentAmount: 'Số tiền thanh toán',
      paymentMethod: 'Phương thức thanh toán',
      paymentMix: 'Cơ cấu thanh toán',
      periodComparison: 'So sánh kỳ',
      previousReportMonth: 'Tháng báo cáo trước',
      priceEndTime: 'Giờ kết thúc giá',
      priceStartTime: 'Giờ bắt đầu giá',
      priceValidFrom: 'Giá hiệu lực từ',
      priceValidUntil: 'Giá hiệu lực đến',
      reportEndDate: 'Ngày kết thúc báo cáo',
      reportStartDate: 'Ngày bắt đầu báo cáo',
      revenueByDayOfWeek: 'Doanh thu theo ngày trong tuần',
      revenueByHour: 'Doanh thu theo giờ',
      salesByDay: 'Doanh thu theo ngày',
      staffConsole: 'Bảng nhân viên',
    },
    chartModes: {
      cheese: 'Tròn',
      columns: 'Cột',
      curves: 'Đường',
    } satisfies Record<StaffReportChartMode, string>,
    commerceTabs: {
      discounts: 'Ưu đãi',
      vouchers: 'Voucher',
      loyalty: 'Điểm thưởng',
    } satisfies Record<StaffCommerceTab, string>,
    attendanceTabs: {
      schedule: 'Lịch làm',
      clock: 'Chấm công',
      timesheet: 'Bảng công',
      leave: 'Nghỉ phép',
      settings: 'Quy định',
    } satisfies Record<StaffAttendanceTab, string>,
    hrTabs: {
      employees: 'Hồ sơ nhân viên',
      schedule: 'Lịch',
      timesheet: 'Bảng công',
      payroll: 'Bảng lương',
      adjustments: 'Thưởng',
      advances: 'Nợ & tạm ứng',
      zalo: 'Zalo Mini App',
      settings: 'Thiết lập HR',
    } satisfies Record<StaffHrTab, string>,
    shiftStatuses: {
      cancelled: 'đã hủy',
      completed: 'hoàn tất',
      draft: 'nháp',
      published: 'đã công bố',
    } satisfies Record<StaffShiftStatus, string>,
    shiftTemplates: {
      afternoon: 'Ca chiều',
      evening: 'Ca tối',
      full_day: 'Cả ngày',
      opening: 'Ca mở cửa',
    } satisfies Record<StaffShiftTemplateId, string>,
    scheduleScopes: {
      all: 'Tất cả bộ phận',
      department: 'Bộ phận của tôi',
      mine: 'Ca của tôi',
    } satisfies Record<StaffScheduleScope, string>,
    attendanceStatuses: {
      absent: 'vắng',
      holiday: 'ngày lễ',
      late: 'đi trễ',
      leave: 'nghỉ phép',
      no_show: 'không đến',
      present: 'có mặt',
    } satisfies Record<StaffAttendanceStatus, string>,
    leaveTypes: {
      annual: 'nghỉ phép năm',
      personal: 'nghỉ cá nhân',
      public_holiday: 'ngày lễ',
      sick: 'nghỉ bệnh',
      unpaid: 'nghỉ không lương',
    } satisfies Record<StaffLeaveType, string>,
    leaveStatuses: {
      approved: 'đã duyệt',
      cancelled: 'đã hủy',
      rejected: 'từ chối',
      requested: 'đang chờ',
    } satisfies Record<StaffLeaveStatus, string>,
    employmentTypes: {
      full_time: 'Toàn thời gian',
      part_time: 'Bán thời gian',
      contractor: 'Cộng tác viên',
      intern: 'Thực tập',
      probation: 'Thử việc',
      probation_full_time: 'Thử việc toàn thời gian',
      probation_part_time: 'Thử việc bán thời gian',
    } satisfies Record<StaffEmploymentType, string>,
    genderOptions: {
      female: 'Nữ',
      male: 'Nam',
      non_binary: 'Phi nhị nguyên',
      prefer_not_to_say: 'Không muốn trả lời',
      other: 'Khác',
    } satisfies Record<StaffGender, string>,
    contractStatuses: {
      active: 'Đang hiệu lực',
      probation: 'Thử việc',
      suspended: 'Tạm ngưng',
      ended: 'Đã kết thúc',
      draft: 'Nháp',
    } satisfies Record<StaffContractStatus, string>,
    adjustmentTypes: {
      bonus: 'Thưởng',
      commission: 'Hoa hồng',
      allowance: 'Phụ cấp',
      lunch_allowance: 'Phụ cấp ăn trưa',
      deduction: 'Khấu trừ',
      advance: 'Tạm ứng',
      debt: 'Nợ',
      debt_repayment: 'Trả nợ',
    } satisfies Record<StaffHrAdjustmentType, string>,
    adjustmentStatuses: {
      draft: 'nháp',
      pending: 'chờ duyệt',
      approved: 'đã duyệt',
      rejected: 'từ chối',
      paid: 'đã trả',
      cancelled: 'đã hủy',
    } satisfies Record<StaffHrAdjustmentStatus, string>,
    payrollStatuses: {
      draft: 'nháp',
      pending: 'đang chờ',
      approved: 'đã duyệt',
      paid: 'đã trả',
      cancelled: 'đã hủy',
    } satisfies Record<StaffPayrollStatus, string>,
    payrollPayCycles: {
      monthly: 'Hàng tháng',
      semi_monthly: 'Nửa tháng',
      weekly: 'Hàng tuần',
      custom: 'Tùy chỉnh',
    } satisfies Record<StaffPayrollPayCycle, string>,
    hrSetupOptionTypes: {
      department: 'Bộ phận',
      job_title: 'Chức danh',
      location: 'Cơ sở',
      contract_status: 'Trạng thái hợp đồng',
      contract_type: 'Loại hợp đồng',
      employment_type: 'Loại việc làm',
      payroll_template: 'Mẫu bảng lương',
      allowance: 'Nhóm phụ cấp',
      deduction: 'Nhóm khấu trừ',
    } satisfies Record<StaffHrSetupOptionType, string>,
    dayTypes: {
      custom: 'tùy chỉnh',
      holiday: 'ngày lễ',
      weekday: 'ngày thường',
      weekend: 'cuối tuần',
    } satisfies Record<StaffPriceRule['day_type'], string>,
    discountDayScopes: {
      all: 'Tất cả ngày',
      fri: 'Thứ Sáu',
      mon: 'Thứ Hai',
      sat: 'Thứ Bảy',
      sun: 'Chủ Nhật',
      thu: 'Thứ Năm',
      tue: 'Thứ Ba',
      wed: 'Thứ Tư',
      weekday: 'Ngày thường',
      weekend: 'Cuối tuần',
    } satisfies Record<StaffDiscountDayScope, string>,
    discountTicketTypes: {
      all: 'Tất cả loại vé',
      birthday: 'Sinh nhật / sự kiện',
      corporate: 'Doanh nghiệp',
      individual: 'Cá nhân',
    } satisfies Record<StaffDiscountTicketType, string>,
    discountTypes: {
      birthday: 'sinh nhật',
      fixed_amount: 'số tiền cố định',
      free_ticket: 'vé miễn phí',
      group: 'nhóm',
      percentage: 'phần trăm',
      resident: 'cư dân',
    } satisfies Record<StaffDiscount['discount_type'], string>,
    gameTypes: {
      escape: 'escape',
      other: 'khác',
      shooting: 'bắn súng',
      tournament: 'giải đấu',
    } satisfies Record<StaffGame['game_type'], string>,
    ticketTypes: {
      birthday: 'Sinh nhật',
      corporate: 'Doanh nghiệp',
      individual: 'Cá nhân',
    } satisfies Record<string, string>,
    audienceOptions: {
      family_friendly: 'Thân thiện gia đình',
      scary: 'Rùng rợn',
      fun: 'Vui nhộn',
      quest: 'Nhiệm vụ',
      teamwork: 'Đồng đội',
      beginner_friendly: 'Dễ cho người mới',
      competitive: 'Thi đấu',
    } satisfies Record<StaffAudience, string>,
    labels: {
      actions: 'Thao tác',
      active: 'Đang bật',
      activeEmployee: 'Nhân viên đang làm',
      inactiveEmployee: 'Nhân viên ngưng làm',
      accountantExports: 'Xuất kế toán',
      arena: 'Arena',
      arenaIds: 'Mã arena',
      attachmentList: 'Danh sách chứng từ',
      annualLeaveDays: 'Ngày phép năm',
      attendance: 'Chấm công',
      attendanceDate: 'Ngày chấm công',
      attendanceSchedule: 'Chấm công & lịch làm',
      bankAccount: 'Số tài khoản',
      bankName: 'Ngân hàng',
      bankTransfer: 'Chuyển khoản',
      baseSalary: 'Lương cơ bản (đ)',
      bestSellingGame: 'Trò chơi bán chạy nhất',
      bookings: 'Đặt chỗ',
      breakMinutes: 'Phút nghỉ',
      calculation: 'Cách tính',
      cancelled: 'Đã hủy',
      cash: 'Tiền mặt',
      capacity: 'Sức chứa',
      checkIns: 'Check-in',
      codeOptional: 'Mã (không bắt buộc)',
      banAccount: 'Cấm tài khoản này luôn',
      compare: 'So sánh',
      compareEditingHint: 'Bấm lịch sẽ chỉnh khoảng so sánh.',
      compareInactiveHint: 'Chọn So sánh phía trên để chỉnh khoảng này.',
      compareRange: 'Khoảng so sánh',
      confirmDeleteWord: 'Nhập DELETE để xác nhận',
      createCustomerAccount: 'Tạo tài khoản khách hàng',
      awardAchievement: 'Mở khóa thành tựu',
      awardAchievementHelp: 'Mở khóa thủ công một thành tựu hiện có khi dữ liệu phiên tự động chưa phản ánh đúng khoảnh khắc thực tế.',
      awardNote: 'Ghi chú nhân viên',
      awardToPlayer: 'Vì sao mở khóa thành tựu này?',
      chooseAchievement: 'Chọn thành tựu',
      choosePlayer: 'Chọn người chơi',
      grantedAwards: 'Mở khóa thủ công',
      createDiscount: 'Tạo ưu đãi',
      createGame: 'Tạo trò chơi',
      createLoyaltyRule: 'Tạo quy tắc điểm',
      createPriceRule: 'Tạo quy tắc giá',
      createVoucher: 'Tạo voucher',
      current: 'hiện tại',
      communitySession: 'Phiên cộng đồng',
      customer: 'Khách hàng',
      guestBooking: 'Đặt chỗ khách vãng lai',
      customerAccountHelp: 'Tên có thể trùng nhau. Mỗi người chơi mới cần một biệt danh riêng. Để trống email để tạo tài khoản số điện thoại với mật khẩu tạm thời.',
      customerAccountPhonePasswordHelp: 'Không có email: VRena tạo mật khẩu tạm thời. Khách đăng nhập, thêm và xác minh email, sau đó tạo mật khẩu riêng.',
      customerTemporaryPassword: 'Mật khẩu tạm thời cho lần đăng nhập đầu',
      customerTemporaryPasswordHelp: 'Chỉ hiển một lần cho khách. Hết hạn sau 24 giờ. Nhân viên không thể xem lại sau đó.',
      customerName: 'Tên khách hàng',
      customerProfile: 'Hồ sơ khách',
      noAwardsYet: 'Chưa có mở khóa thủ công.',
      noPlayersFound: 'Không tìm thấy người chơi.',
      optional: 'không bắt buộc',
      password: 'Mật khẩu',
      confirmPassword: 'Xác nhận mật khẩu',
      sendAward: 'Mở khóa thành tựu',
      date: 'Ngày',
      dateRange: 'Khoảng ngày',
      dayType: 'Loại ngày',
      deleteReason: 'Lý do',
      description: 'Mô tả',
      audience: 'Đối tượng',
      discount: 'Ưu đãi',
      discountRuleHelp: 'Ưu đãi được áp dụng tự động khi khớp quy tắc. Voucher hoạt động khi khách nhập mã voucher.',
      discountConditions: 'Điều kiện',
      discountType: 'Loại ưu đãi',
      discountVoucher: 'Ưu đãi / voucher',
      discounts: 'Ưu đãi',
      duration: 'Thời lượng',
      escapeChapters: 'Số chapter Escape',
      email: 'E-mail',
      employeeCode: 'Mã nhân viên',
      attendanceNumber: 'Mã chấm công',
      employmentType: 'Loại hợp đồng',
      end: 'Kết thúc',
      endDate: 'Ngày kết thúc',
      contractStatus: 'Trạng thái hợp đồng',
      contractType: 'Loại hợp đồng',
      contractStartDate: 'Ngày bắt đầu HĐ',
      contractEndDate: 'Ngày kết thúc HĐ',
      editingRange: 'Đang chỉnh',
      emergencyContact: 'Liên hệ khẩn cấp',
      estimatedPayroll: 'Lương tạm tính',
      exportFormat: 'Định dạng',
      exportLanguage: 'Ngôn ngữ',
      exportReport: 'Báo cáo',
      exportStore: 'Cơ sở',
      holidayHours: 'Giờ ngày lễ',
      hours: 'Giờ',
      hourlyRate: 'Lương gross theo giờ (đ)',
      monthlyGross: 'Lương gross tháng (đ)',
      missingDocuments: 'Thiếu chứng từ',
      filterByRole: 'Lọc theo vai trò',
      game: 'Trò chơi',
      guideGameplay: 'GamePlay',
      guideLanguage: 'Ngôn ngữ hướng dẫn',
      guideSummary: 'Tóm tắt hướng dẫn',
      guideTips: 'Mẹo hướng dẫn',
      gamePhoto: 'Ảnh trò chơi',
      games: 'Trò chơi',
      imageUrl: 'URL ảnh',
      includeAttachments: 'Kèm danh sách chứng từ',
      internalNote: 'Ghi chú nội bộ',
      jobTitle: 'Chức danh',
      department: 'Bộ phận',
      lateNoShow: 'Đi trễ / không đến',
      legalName: 'Tên pháp lý',
      leaveHours: 'Giờ nghỉ',
      leaveBalance: 'Phép còn lại',
      leaveType: 'Loại nghỉ',
      location: 'Cơ sở',
      mainWorkLocation: 'Cơ sở làm việc chính',
      payrollLocation: 'Cơ sở tính lương',
      managerNote: 'Ghi chú quản lý',
      maxPlayersArena: 'Số người tối đa / arena',
      maxPlayers: 'Số người tối đa',
      maxDiscountAmount: 'Giảm tối đa',
      maxUses: 'Số lần dùng tối đa',
      limitByHour: 'Giới hạn theo giờ',
      minPlayers: 'Số người tối thiểu',
      minimumSpend: 'Chi tiêu tối thiểu',
      name: 'Tên',
      newBooking: 'Đặt chỗ mới',
      nickname: 'Biệt danh',
      noLinkedOrder: 'Chưa có đơn liên kết',
      no: 'Không',
      noShows: 'Không đến',
      nightHours: 'Giờ đêm',
      nightWindow: 'Khung giờ đêm',
      notes: 'Ghi chú',
      order: 'Đơn',
      orderStatus: 'Trạng thái đơn',
      orders: 'Đơn hàng',
      off: 'Tắt',
      operationsCalendar: 'Lịch vận hành',
      operationsDate: 'Ngày vận hành',
      paid: 'Đã trả',
      payment: 'Thanh toán',
      paymentSplits: 'Tách thanh toán',
      paymentStatus: 'Trạng thái thanh toán',
      paymentMix: 'Cơ cấu thanh toán',
      payrollLink: 'Liên kết chấm công / lương',
      payrollNote: 'Ghi chú lương',
      payrollRun: 'Bảng lương',
      payrollCode: 'Mã bảng lương',
      payrollName: 'Tên bảng lương',
      payCycle: 'Chu kỳ lương',
      payslipPreview: 'Phiếu lương Việt Nam',
      periodStart: 'Bắt đầu kỳ',
      periodEnd: 'Kết thúc kỳ',
      perCustomerLimit: 'Giới hạn / khách',
      perVndSpent: 'Theo VND chi tiêu',
      phone: 'Điện thoại',
      personalEmail: 'Email cá nhân',
      personalPhone: 'SĐT cá nhân',
      profilePhoto: 'Ảnh hồ sơ',
      cvDocument: 'CV',
      profileCompletion: 'Độ hoàn thiện hồ sơ',
      players: 'Người chơi',
      addPlayer: 'Thêm người chơi',
      sessionFields: 'Thông tin phiên',
      participantResults: 'Kết quả người chơi',
      chapterTimes: 'Thời gian chapter',
      chapter: 'Chapter',
      score: 'Điểm',
      place: 'Hạng',
      accuracy: 'Độ chính xác',
      projectiles: 'Số lần trúng',
      movement: 'Quãng đường',
      escapeTime: 'Thời gian Escape',
      loyaltyPoints: 'Điểm thưởng',
      pointsEarned: 'Điểm nhận được',
      pointsExpireAfterDays: 'Điểm hết hạn sau số ngày',
      redeemValue: 'Giá trị đổi điểm',
      privateSession: 'Phiên riêng tư',
      priceArenaSlot: 'Giá / slot arena (đ)',
      pricePlayer: 'Giá / người (đ)',
      priceRule: 'Quy tắc giá',
      priceRules: 'Quy tắc giá',
      privateEmployeeProfile: 'Hồ sơ nhân viên riêng tư',
      address: 'Địa chỉ',
      dateOfBirth: 'Ngày sinh',
      gender: 'Giới tính',
      nationalId: 'CCCD/CMND',
      regularHours: 'Giờ thường',
      remaining: 'Còn lại',
      restoreDeletedRecords: 'Khôi phục dữ liệu đã xóa',
      deletedBy: 'Đã xóa bởi',
      referenceRange: 'Khoảng tham chiếu',
      reportRange: 'Khoảng báo cáo',
      roleExplanation: 'Giải thích vai trò',
      roleFor: 'Vai trò cho',
      roles: 'Vai trò',
      rounds: 'Vòng',
      rule: 'Quy tắc',
      ruleName: 'Tên quy tắc',
      sales: 'Doanh thu',
      salesTrend: 'Xu hướng doanh thu',
      revenueByDayOfWeek: 'Doanh thu theo ngày trong tuần',
      revenueByHour: 'Doanh thu theo giờ',
      searchUsers: 'Tìm người dùng',
      selectedRange: 'Khoảng đã chọn',
      sessions: 'Phiên',
      scheduledHours: 'Giờ đã xếp',
      shiftDate: 'Ngày ca',
      shiftList: 'Danh sách ca',
      shiftRole: 'Vị trí ca',
      scheduleScope: 'Chế độ xem lịch',
      shiftTemplate: 'Mẫu ca',
      sortBy: 'Sắp xếp theo',
      slug: 'Slug',
      standardDay: 'Độ dài ngày chuẩn',
      standardDayHelp: 'Dùng HH:mm. Ví dụ: 07:15 = 7 giờ 15 phút.',
      standardDayPresets: 'Mẫu ngày chuẩn',
      standardBreakMinutes: 'Phút nghỉ chuẩn',
      standardShiftTemplates: 'Mẫu ca chuẩn',
      standardWeek: 'Tuần chuẩn',
      start: 'Bắt đầu',
      startDate: 'Ngày bắt đầu',
      status: 'Trạng thái',
      staffMember: 'Nhân viên',
      socialInsurance: 'Mã BHXH',
      standardMonthlyDays: 'Ngày công chuẩn / tháng',
      standardMonthlyHours: 'Giờ công chuẩn / tháng',
      subtotal: 'Tạm tính',
      summary: 'Tóm tắt',
      taxCodeEmployee: 'Mã số thuế',
      time: 'Giờ',
      ticketBookings: 'Đặt vé',
      ticketType: 'Loại vé',
      total: 'Tổng',
      totalCompanyCost: 'Tổng chi phí công ty',
      totalGross: 'Tổng gross',
      totalNet: 'Tổng net',
      totalPaid: 'Đã thanh toán',
      totalSales: 'Tổng doanh thu',
      type: 'Loại',
      uniqueDiscount: 'Ưu đãi riêng',
      used: 'đã dùng',
      value: 'Giá trị',
      validFrom: 'Hiệu lực từ',
      validUntil: 'Hiệu lực đến',
      validUntilHelp: 'không bắt buộc, mặc định là mãi mãi',
      voucherCodeRequired: 'Mã voucher *',
      vouchers: 'Voucher',
      weeklyRange: 'Tuần',
      weeklySchedule: 'Lịch tuần',
      allDays: 'Tất cả ngày',
      allTicketTypes: 'Tất cả loại vé',
      overtimeHours: 'Giờ tăng ca',
      overtimePay: 'Tiền tăng ca',
      paidLeave: 'Nghỉ phép hưởng lương',
      overtimeMonthlyCap: 'Giới hạn tăng ca / tháng',
      overtimeYearlyCap: 'Giới hạn tăng ca / năm',
      normalOvertimeMultiplier: 'Hệ số tăng ca thường',
      nightOvertimeMultiplier: 'Hệ số tăng ca đêm',
      holidayOvertimeMultiplier: 'Hệ số ngày lễ',
      lunchAllowance: 'Phụ cấp ăn trưa / ngày',
      mealAllowance: 'Phụ cấp bữa ăn',
      restPeriodHours: 'Nghỉ tối thiểu (giờ)',
      restWarnings: 'Cảnh báo nghỉ',
      employeeContributionRate: 'Tỷ lệ NLĐ đóng %',
      employerContributionRate: 'Tỷ lệ công ty đóng %',
      pitWithholdingRate: 'Tạm khấu trừ TNCN %',
      dependentsCount: 'Người phụ thuộc',
      grossIncome: 'Thu nhập gross',
      netIncome: 'Thu nhập net',
      companyCost: 'Chi phí công ty',
      allowances: 'Phụ cấp',
      bonuses: 'Thưởng',
      advances: 'Tạm ứng',
      deductions: 'Khấu trừ',
      employeeContributions: 'NLĐ đóng',
      employerContributions: 'Công ty đóng',
      pitWithheld: 'TNCN tạm khấu trừ',
      outstandingDebt: 'Nợ còn lại',
      workedHours: 'Giờ làm',
      yes: 'Có',
    },
    loyaltyCalculation: {
      per_booking: 'Theo mỗi đặt chỗ',
      per_player: 'Theo mỗi người chơi',
      per_visit: 'Theo mỗi lượt đến/check-in',
      per_vnd_spent: 'Theo chi tiêu',
    } satisfies Record<StaffLoyaltyRule['calculation_type'], string>,
    messages: {
      clickUploadGamePhoto: 'Bấm để tải ảnh trò chơi',
      accountDeleteBanNote: 'Thông tin cấm sẽ gắn với hồ sơ đã xóa để kiểm tra sau.',
      accountDeleteBody: 'Thao tác này xóa mềm hồ sơ người dùng và gỡ khỏi danh sách đang hoạt động. Phiên chơi, điểm, đơn hàng và nhật ký lịch sử vẫn được giữ.',
      accountDeleteTitle: 'Xóa tài khoản?',
      operationDeleteBody: 'Mục này sẽ biến mất khỏi danh sách Phiên và Tickets. Người chơi liên quan được xóa và đơn hàng liên kết được chuyển sang đã hủy.',
      operationDeleteTitle: 'Xóa phiên hoặc vé này?',
      accountDeleted: 'Đã xóa tài khoản.',
      accountDeleting: 'Đang xóa tài khoản...',
      accountDeleteConfirmationHelp: 'Nhập chính xác DELETE để mở khóa thao tác này.',
      accountantExportHelp: 'Chọn bộ lọc, loại báo cáo và định dạng, rồi tải xuống.',
      accountantExportSourcePending: 'Bảng dữ liệu chi tiết chưa được cấu hình. File này gồm phần tóm tắt báo cáo đang có cho khoảng đã chọn.',
      accountantAttachmentsExcelOnly: 'Danh sách chứng từ chỉ có trong file Excel.',
      reportDownloadFailed: 'Không thể tải báo cáo. Vui lòng thử lại.',
      reportDownloadStarted: 'Đã bắt đầu tải xuống.',
      attendanceIntro: 'Xếp ca, chấm công, nghỉ phép, tăng ca và kiểm tra quy định lao động Việt Nam trong một nơi.',
      attendanceReadOnly: 'Chế độ chỉ xem. Viewer có thể xem chấm công nhưng không thể lưu thay đổi.',
      attendanceRulesSaved: 'Đã lưu quy định chấm công.',
      attendanceSaved: 'Đã lưu chấm công.',
      customerAccountEmailRequired: 'Nhập email khách hàng.',
      customerAccountInvited: 'Đã tạo tài khoản khách hàng. Đã gửi yêu cầu tạo mật khẩu.',
      customerAccountNameRequired: 'Nhập tên khách hàng.',
      customerAccountNicknameRequired: 'Nhập biệt danh khách hàng.',
      customerAccountNicknameTaken: 'Biệt danh này đã được sử dụng.',
      customerAccountPasswordMismatch: 'Mật khẩu xác nhận không khớp.',
      customerAccountPasswordRequired: 'Nhập mật khẩu có ít nhất 6 ký tự.',
      customerAccountPhoneCreated: 'Đã tạo tài khoản bằng số điện thoại. Hãy đưa mật khẩu tạm thời bên dưới cho khách.',
      customerTemporaryPasswordCopied: 'Đã sao chép mật khẩu tạm thời.',
      customerAccountPhoneRequired: 'Nhập số điện thoại khách hàng hợp lệ.',
      guestBookingHelp: 'Không tạo hồ sơ khách hàng, tên, thông tin liên hệ hay thống kê người chơi. Thanh toán, số người, ngày, giờ, thời lượng và trò chơi vẫn được lưu.',
      achievementAwarded: 'Đã mở khóa thành tựu cho người chơi.',
      achievementAlreadyAwarded: 'Người chơi đã có thành tựu này.',
      achievementAwardSelectPlayer: 'Chọn người chơi trước.',
      discountSaved: 'Đã lưu ưu đãi.',
      draftShiftCreated: 'Đã tạo ca nháp.',
      draftShiftExists: 'Ca nháp này đã tồn tại cho nhân viên và ngày này.',
      employeeProfileIntro: 'Thông tin nhân sự riêng tư được liên kết với chấm công và tính lương. Chỉ vai trò HR nội bộ xem được.',
      employeeProfileSaved: 'Đã lưu hồ sơ nhân viên.',
      hrIntro: 'Trung tâm HR của công ty cho hồ sơ nhân viên, lịch làm, bảng công, lương, phiếu lương, thưởng, tạm ứng và thiết lập.',
      hrSetupUnavailable: 'Áp dụng migration HR để lưu thiết lập HR, thưởng, bảng lương và tài liệu.',
      hrSettingsSaved: 'Đã lưu thiết lập HR.',
      hrSetupOptionSaved: 'Đã lưu tùy chọn HR.',
      adjustmentSaved: 'Đã lưu khoản điều chỉnh HR.',
      adjustmentApproved: 'Đã duyệt khoản điều chỉnh.',
      payrollGenerated: 'Đã tạo bảng lương nháp.',
      payrollApproved: 'Đã duyệt bảng lương.',
      profilePhotoHelp: 'JPG, PNG hoặc WEBP · tối đa 2 MB.',
      cvHelp: 'PDF, DOC hoặc DOCX · tối đa 10 MB.',
      profilePhotoTooLarge: 'Ảnh hồ sơ phải từ 2 MB trở xuống.',
      cvTooLarge: 'CV phải từ 10 MB trở xuống.',
      documentUploaded: 'Đã tải tài liệu.',
      documentUploadFailed: 'Tải tài liệu thất bại.',
      noAdjustments: 'Chưa có khoản điều chỉnh HR trong kỳ này.',
      noPayrollRuns: 'Chưa có bảng lương.',
      noHrDocuments: 'Chưa tải tài liệu HR.',
      noScheduleShifts: 'Chưa có ca làm trong kỳ này.',
      inactiveEmployeePlanningBlocked: 'Nhân viên ngưng làm: bật lại hồ sơ nhân viên trước khi xếp ca mới.',
      gamePhotoSmall: 'Ảnh trò chơi phải từ 2 MB trở xuống.',
      gamePhotoType: 'Ảnh trò chơi phải là JPG, PNG hoặc WEBP.',
      gamePhotoUploaded: 'Đã tải ảnh. Lưu trò chơi để giữ ảnh.',
      gameGuideHelp: 'Chọn ngôn ngữ, rồi sửa tóm tắt, GamePlay và mẹo chỉ cho trò chơi này. Mỗi dòng là một mục GamePlay hoặc mẹo.',
      gameSaved: 'Đã lưu trò chơi.',
      loyaltyIntro: 'Thiết lập cách khách hàng nhận điểm. Đổi điểm sẽ dùng các quy tắc này sau.',
      loyaltyRuleSaved: 'Đã lưu quy tắc điểm.',
      loyaltySingleActiveConfirm: 'Chỉ một quy tắc điểm được active. Lưu quy tắc này sẽ tắt {rule} nhưng vẫn giữ lại để phân tích. Tiếp tục?',
      loyaltyPointsUpdated: 'Đã cập nhật điểm thưởng.',
      loyaltyPointsUpdating: 'Đang cập nhật điểm thưởng...',
      leaveSaved: 'Đã lưu yêu cầu nghỉ phép.',
      leaveUpdated: 'Đã cập nhật yêu cầu nghỉ phép.',
      noAttendanceLogs: 'Chưa có chấm công trong tuần này.',
      noDiscounts: 'Chưa có ưu đãi.',
      noLeaveRequests: 'Chưa có yêu cầu nghỉ phép trong tuần này.',
      noLoyaltyRules: 'Chưa có quy tắc điểm.',
      noOrders: 'Không có đơn trong khoảng này.',
      noSales: 'Chưa có doanh thu trong kỳ này.',
      noShifts: 'Chưa có ca làm trong tuần này.',
      noStaffProfiles: 'Chưa có hồ sơ nhân viên.',
      noSoftDeleted: 'Không có dữ liệu xóa mềm.',
      noVouchers: 'Chưa có voucher.',
      orderConfirmed: 'Đơn {order} đã xác nhận · {total}',
      orderCreating: 'Đang tạo đơn...',
      orderEditInvalid: 'Chọn trò chơi, ngày và giờ, sau đó nhập tổng tiền VND nguyên từ 0 trở lên.',
      orderUpdated: 'Đã cập nhật đơn.',
      priceRuleSaved: 'Đã lưu quy tắc giá.',
      readOnlyBooking: 'Chế độ chỉ xem. Viewer có thể xem luồng này nhưng không thể tạo đặt chỗ.',
      readOnlyCommerce: 'Chế độ chỉ xem. Viewer có thể xem quy tắc nhưng không thể lưu thay đổi.',
      readOnlyGames: 'Chế độ chỉ xem. Viewer có thể xem trò chơi nhưng không thể lưu thay đổi.',
      readOnlyPrices: 'Chế độ chỉ xem. Viewer có thể xem quy tắc giá nhưng không thể lưu thay đổi.',
      restoreIntro: 'Chỉ Owner. Khôi phục sẽ xóa deleted_at, deleted_by và delete_reason.',
      restoringRecord: 'Đang khôi phục...',
      recordRestored: 'Đã khôi phục dữ liệu.',
      roleSaveFailed: 'Chưa lưu được vai trò. Hãy chạy SQL Supabase mới nhất rồi thử lại.',
      roleSaveMismatch: 'Chưa lưu được vai trò. Supabase vẫn trả về vai trò khác.',
      roleUpdated: 'Đã cập nhật vai trò.',
      roleUpdating: 'Đang cập nhật vai trò...',
      shiftSaved: 'Đã lưu ca làm.',
      staffTooManyAttempts: 'Quá nhiều lần thử. Vui lòng chờ một chút rồi thử lại.',
      planningConflictDailyLimit: 'Vượt giờ chuẩn trong ngày.',
      planningConflictLeave: 'Có nghỉ phép đã duyệt trong ngày này.',
      planningConflictOverlap: 'Trùng ca khác.',
      planningGridHelp: 'Bấm ô để tạo ca nháp. Kéo thẻ ca để chuyển ngày/người.',
      previousWeekCopied: 'Đã sao chép tuần trước thành ca nháp.',
      previousWeekEmpty: 'Không có ca nào trong tuần trước.',
      previousWeekNoNew: 'Tuần này đã có các ca đó. Không sao chép thêm.',
      weekPublished: 'Đã công bố tuần.',
      uniqueDiscountHelp: 'Ưu đãi dùng một lần cho đặt chỗ này. Không tạo voucher dùng lại.',
      uploadGamePhoto: 'Đang tải ảnh trò chơi...',
      noOperationSessions: 'Không có phiên hoặc đặt vé trong ngày này.',
      operationsIntro: 'Quản lý phiên, đặt vé, sức chứa, thanh toán, check-in, người chơi và kết quả trong một nơi.',
      operationSessionSaved: 'Đã cập nhật phiên.',
      operationParticipantSaved: 'Đã cập nhật người chơi.',
      operationParticipantAdded: 'Đã thêm người chơi.',
      operationParticipantRemoved: 'Đã xóa người chơi.',
      operationSessionDeleted: 'Đã xóa phiên.',
      operationSessionDeleting: 'Đang xóa phiên...',
      voucherCodeRequired: 'Cần nhập mã voucher.',
      voucherSaved: 'Đã lưu voucher.',
    },
    orderStatuses: {
      cancelled: 'đã hủy',
      completed: 'hoàn tất',
      confirmed: 'đã xác nhận',
      draft: 'nháp',
      no_show: 'không đến',
      paid: 'đã thanh toán',
      partially_paid: 'thanh toán một phần',
      refunded: 'đã hoàn tiền',
    } satisfies Record<StaffOrder['order_status'], string>,
    paymentMethods: {
      bank_transfer: 'Chuyển khoản',
      cash: 'Tiền mặt',
    } satisfies Record<StaffPaymentMethod, string>,
    roles: {
      admin: 'Admin',
      cashier: 'Nhân viên văn phòng',
      employee: 'Nhân viên (chỉ dùng PIN)',
      manager: 'Quản lý',
      owner: 'Owner',
      player: 'Player',
      staff: 'Nhân viên',
      viewer: 'Viewer',
    } satisfies Record<StaffRole, string>,
    roleSorts: {
      created_desc: 'Mới tạo gần đây',
      email_asc: 'E-mail A-Z',
      name_asc: 'Tên A-Z',
      name_desc: 'Tên Z-A',
      role_asc: 'Vai trò thấp-cao',
      role_desc: 'Vai trò cao-thấp',
    } satisfies Record<StaffRoleSort, string>,
    reportRangePresets: {
      today: 'Phiên',
      yesterday: 'Hôm qua',
      this_week: 'Tuần này',
      last_week: 'Tuần trước',
      this_month: 'Tháng này',
      last_month: 'Tháng trước',
      last_30: '30 ngày qua',
      last_60: '60 ngày qua',
      last_90: '90 ngày qua',
    } satisfies Record<StaffReportRangePreset, string>,
    reportWeekdays: ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'],
    roleHelp: [
      { title: 'Owner', body: 'Toàn quyền Staff Console, quản lý vai trò, công cụ khôi phục và mọi tính năng khách hàng.' },
      { title: 'Admin', body: 'Toàn quyền vận hành hằng ngày và quản lý vai trò dưới Owner. Khôi phục chỉ dành cho Owner.' },
      { title: 'Office Staff', body: 'Quyền xem như Viewer, được chỉnh báo cáo và toàn quyền chỉnh Chấm công.' },
      { title: 'Viewer', body: 'Dùng app như người chơi, xem toàn bộ Staff Console, chỉnh hoặc tải báo cáo. Dữ liệu staff còn lại chỉ xem.' },
      { title: 'Nhân viên (chỉ dùng PIN)', body: 'Không có quyền truy cập web app cá nhân. Nhân viên nhập PIN trên tài khoản cửa hàng dùng chung và nhận quyền Quản lý hoặc Nhân viên đã cấu hình trong HR.' },
      { title: 'Player', body: 'Chỉ có app khách hàng. Không có quyền Staff Console.' },
    ],
    tabs: {
      clientProfile: 'Hồ sơ khách',
      discounts: 'Ưu đãi',
      attendance: 'Chấm công',
      games: 'Trò chơi',
      hr: 'HR',
      new: 'Đặt chỗ mới',
      orders: 'Đơn hàng',
      prices: 'Giá',
      report: 'Báo cáo ngày',
      restore: 'Khôi phục',
      roles: 'Vai trò',
      today: 'Hôm nay',
    } satisfies Record<StaffTab, string>,
    tabGroups: {
      admin: 'Admin',
      operate: 'Vận hành',
      reports: 'Báo cáo',
      setup: 'Thiết lập',
      team: 'Nhân sự',
    } satisfies Record<StaffTabGroupId, string>,
  },
} as const

export type StaffConsoleCopy = (typeof staffConsoleText)[StaffConsoleLanguage]
