-- Consent-based, first-party product analytics for player-facing routes.
-- Raw IP addresses and search text are intentionally excluded from storage.

create table public.app_analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  client_id uuid not null,
  session_id uuid not null,
  profile_id uuid references public.profiles(id) on delete set null,
  event_name text not null check (event_name in ('page_view', 'engagement', 'search')),
  path text not null check (char_length(path) between 1 and 180),
  device_class text not null check (device_class in ('mobile', 'tablet', 'desktop')),
  browser_family text not null check (char_length(browser_family) between 1 and 40),
  os_family text not null check (char_length(os_family) between 1 and 40),
  viewport_bucket text not null check (char_length(viewport_bucket) between 1 and 24),
  referrer_host text check (referrer_host is null or char_length(referrer_host) <= 120),
  acquisition_source text check (acquisition_source is null or char_length(acquisition_source) <= 80),
  acquisition_medium text check (acquisition_medium is null or char_length(acquisition_medium) <= 80),
  acquisition_campaign text check (acquisition_campaign is null or char_length(acquisition_campaign) <= 120),
  duration_seconds integer check (duration_seconds is null or duration_seconds between 1 and 1800),
  search_surface text check (search_surface is null or char_length(search_surface) <= 80),
  search_query_length smallint check (search_query_length is null or search_query_length between 0 and 240),
  search_result_count integer check (search_result_count is null or search_result_count between 0 and 10000)
);

comment on table public.app_analytics_events is
  'Opted-in first-party product analytics. Does not store raw IP addresses, full URLs, or search text.';
comment on column public.app_analytics_events.client_id is
  'Random browser identifier created only after analytics consent.';
comment on column public.app_analytics_events.profile_id is
  'Authenticated profile when available; reports expose aggregate data only.';

create index app_analytics_events_created_at_idx
  on public.app_analytics_events (created_at desc);
create index app_analytics_events_event_created_idx
  on public.app_analytics_events (event_name, created_at desc);
create index app_analytics_events_session_created_idx
  on public.app_analytics_events (session_id, created_at, id);
create index app_analytics_events_path_created_idx
  on public.app_analytics_events (path, created_at desc);
create index app_analytics_events_profile_created_idx
  on public.app_analytics_events (profile_id, created_at desc)
  where profile_id is not null;

alter table public.app_analytics_events enable row level security;
revoke all on table public.app_analytics_events from public, anon, authenticated;
grant select, insert, update, delete on table public.app_analytics_events to service_role;
grant usage, select on sequence public.app_analytics_events_id_seq to service_role;

-- Extend the trusted server-only limiter with a dedicated analytics action.
create or replace function private.consume_rate_limit(
  p_action text,
  p_limit integer,
  p_window_seconds integer,
  p_subject text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_now timestamptz := now();
  v_window_started_at timestamptz;
  v_reset_at timestamptz;
  v_actor text := coalesce((select auth.uid())::text, '');
  v_subject text;
  v_hash_material text;
  v_hash text;
  v_count integer;
begin
  if p_action not in (
    'login_attempt',
    'otp_request',
    'join_leave',
    'booking_attempt',
    'booking_update_email',
    'admin_destructive',
    'password_reset',
    'password_reset_ip',
    'invite_player',
    'session_message',
    'customer_invite',
    'customer_invite_actor',
    'voucher_quote',
    'staff_config_write',
    'product_analytics'
  ) then
    raise exception 'Unknown rate limit action.';
  end if;

  if coalesce(p_limit, 0) < 1 or coalesce(p_window_seconds, 0) < 1 then
    raise exception 'Invalid rate limit configuration.';
  end if;

  v_subject := lower(coalesce(nullif(btrim(p_subject), ''), v_actor, 'anonymous'));
  v_hash_material := lower(p_action) || ':' || v_actor || ':' || v_subject;

  if to_regprocedure('extensions.digest(text, text)') is not null then
    execute 'select encode(extensions.digest($1, $2), ''hex'')'
      into v_hash
      using v_hash_material, 'sha256';
  elsif to_regprocedure('public.digest(text, text)') is not null then
    execute 'select encode(public.digest($1, $2), ''hex'')'
      into v_hash
      using v_hash_material, 'sha256';
  else
    v_hash := md5(v_hash_material);
  end if;

  v_window_started_at := to_timestamp(floor(extract(epoch from v_now) / p_window_seconds) * p_window_seconds);
  v_reset_at := v_window_started_at + make_interval(secs => p_window_seconds);

  delete from public.security_rate_limits
  where reset_at < v_now - interval '1 day';

  insert into public.security_rate_limits (
    subject_hash,
    action,
    window_started_at,
    reset_at,
    attempt_count,
    last_seen_at
  )
  values (
    v_hash,
    p_action,
    v_window_started_at,
    v_reset_at,
    1,
    v_now
  )
  on conflict (subject_hash, action, window_started_at)
  do update
  set attempt_count = public.security_rate_limits.attempt_count + 1,
      last_seen_at = excluded.last_seen_at,
      reset_at = excluded.reset_at
  returning attempt_count into v_count;

  if v_count > p_limit then
    raise exception 'Too many attempts. Please wait a moment and try again.';
  end if;

  return jsonb_build_object(
    'allowed', true,
    'remaining', greatest(0, p_limit - v_count),
    'reset_at', v_reset_at
  );
end;
$function$;

revoke all on function private.consume_rate_limit(text, integer, integer, text)
  from public, anon, authenticated;
grant execute on function private.consume_rate_limit(text, integer, integer, text)
  to service_role;

create or replace function public.staff_product_analytics_report(
  p_start_date date,
  p_end_date date,
  p_compare_start date default null,
  p_compare_end date default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $function$
declare
  v_start date := least(p_start_date, p_end_date);
  v_end date := greatest(p_start_date, p_end_date);
  v_compare_start date := case
    when p_compare_start is null or p_compare_end is null then null
    else least(p_compare_start, p_compare_end)
  end;
  v_compare_end date := case
    when p_compare_start is null or p_compare_end is null then null
    else greatest(p_compare_start, p_compare_end)
  end;
  v_payload jsonb;
begin
  if not public.is_staff_console_user(20) then
    raise exception 'Staff Console access required';
  end if;

  with ranges as (
    select 'current'::text as range_key, v_start as range_start, v_end as range_end
    union all
    select 'comparison', v_compare_start, v_compare_end
    where v_compare_start is not null and v_compare_end is not null
  ),
  scoped_events as (
    select
      ranges.range_key,
      event.*
    from ranges
    join public.app_analytics_events event
      on (event.created_at at time zone 'Asia/Ho_Chi_Minh')::date
        between ranges.range_start and ranges.range_end
    where event.path !~ '^/(staff|hr|admin)(/|$)'
  ),
  summaries as (
    select
      ranges.range_key,
      count(distinct event.session_id)::integer as sessions,
      count(distinct event.client_id)::integer as visitors,
      count(distinct event.client_id) filter (where event.profile_id is not null)::integer as signed_in_visitors,
      count(*) filter (where event.event_name = 'page_view')::integer as page_views,
      count(*) filter (where event.event_name = 'search')::integer as searches,
      coalesce(sum(event.duration_seconds) filter (where event.event_name = 'engagement'), 0)::integer as engagement_seconds,
      max(event.created_at) as latest_event_at
    from ranges
    left join scoped_events event on event.range_key = ranges.range_key
    group by ranges.range_key
  ),
  summary_json as (
    select
      range_key,
      jsonb_build_object(
        'sessions', sessions,
        'visitors', visitors,
        'signedInVisitors', signed_in_visitors,
        'pageViews', page_views,
        'searches', searches,
        'engagementSeconds', engagement_seconds,
        'averageSessionSeconds', case when sessions = 0 then 0 else round(engagement_seconds::numeric / sessions, 0) end,
        'pagesPerSession', case when sessions = 0 then 0 else round(page_views::numeric / sessions, 1) end,
        'searchRate', case when sessions = 0 then 0 else round((searches::numeric / sessions) * 100, 1) end,
        'signedInShare', case when visitors = 0 then 0 else round((signed_in_visitors::numeric / visitors) * 100, 1) end,
        'latestEventAt', latest_event_at
      ) as summary
    from summaries
  ),
  series_days as (
    select generate_series(v_start, least(v_end, v_start + 179), interval '1 day')::date as day
  ),
  activity_series as (
    select
      day.day,
      count(*) filter (where event.event_name = 'page_view')::integer as page_views,
      count(distinct event.session_id)::integer as sessions,
      count(*) filter (where event.event_name = 'search')::integer as searches
    from series_days day
    left join scoped_events event
      on event.range_key = 'current'
      and (event.created_at at time zone 'Asia/Ho_Chi_Minh')::date = day.day
    group by day.day
  ),
  top_pages as (
    select
      event.path,
      count(*) filter (where event.event_name = 'page_view')::integer as page_views,
      count(distinct event.client_id) filter (where event.event_name = 'page_view')::integer as visitors,
      coalesce(sum(event.duration_seconds) filter (where event.event_name = 'engagement'), 0)::integer as engagement_seconds
    from scoped_events event
    where event.range_key = 'current'
    group by event.path
    having count(*) filter (where event.event_name = 'page_view') > 0
    order by page_views desc, visitors desc, event.path
    limit 8
  ),
  page_sequence as (
    select
      event.session_id,
      event.path as to_path,
      lag(event.path) over (partition by event.session_id order by event.created_at, event.id) as from_path
    from scoped_events event
    where event.range_key = 'current'
      and event.event_name = 'page_view'
  ),
  transitions as (
    select
      from_path,
      to_path,
      count(*)::integer as transitions
    from page_sequence
    where from_path is not null and from_path <> to_path
    group by from_path, to_path
    order by transitions desc, from_path, to_path
    limit 8
  ),
  device_mix as (
    select
      event.device_class,
      count(distinct event.session_id)::integer as sessions
    from scoped_events event
    where event.range_key = 'current'
      and event.event_name = 'page_view'
    group by event.device_class
    order by sessions desc, event.device_class
  ),
  session_acquisition as (
    select distinct on (event.session_id)
      event.session_id,
      coalesce(nullif(event.acquisition_source, ''), nullif(event.referrer_host, ''), 'Direct') as source,
      coalesce(nullif(event.acquisition_medium, ''), case when event.referrer_host is null then 'direct' else 'referral' end) as medium
    from scoped_events event
    where event.range_key = 'current'
      and event.event_name = 'page_view'
    order by event.session_id, event.created_at, event.id
  ),
  acquisition_mix as (
    select source, medium, count(*)::integer as sessions
    from session_acquisition
    group by source, medium
    order by sessions desc, source
    limit 8
  ),
  search_surfaces as (
    select
      coalesce(nullif(event.search_surface, ''), 'Other') as surface,
      count(*)::integer as searches,
      round(avg(event.search_query_length)::numeric, 1) as average_query_length,
      round((avg(event.search_result_count) filter (where event.search_result_count is not null))::numeric, 1) as average_results
    from scoped_events event
    where event.range_key = 'current'
      and event.event_name = 'search'
    group by coalesce(nullif(event.search_surface, ''), 'Other')
    order by searches desc, surface
    limit 8
  )
  select jsonb_build_object(
    'summary', coalesce((select summary from summary_json where range_key = 'current'), '{}'::jsonb),
    'comparisonSummary', coalesce((select summary from summary_json where range_key = 'comparison'), '{}'::jsonb),
    'activitySeries', coalesce((
      select jsonb_agg(jsonb_build_object(
        'date', day::text,
        'pageViews', page_views,
        'sessions', sessions,
        'searches', searches
      ) order by day)
      from activity_series
    ), '[]'::jsonb),
    'topPages', coalesce((
      select jsonb_agg(jsonb_build_object(
        'path', path,
        'pageViews', page_views,
        'visitors', visitors,
        'engagementSeconds', engagement_seconds
      ) order by page_views desc, visitors desc, path)
      from top_pages
    ), '[]'::jsonb),
    'transitions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'fromPath', from_path,
        'toPath', to_path,
        'transitions', transitions
      ) order by transitions desc, from_path, to_path)
      from transitions
    ), '[]'::jsonb),
    'deviceMix', coalesce((
      select jsonb_agg(jsonb_build_object(
        'deviceClass', device_class,
        'sessions', sessions
      ) order by sessions desc, device_class)
      from device_mix
    ), '[]'::jsonb),
    'acquisitionMix', coalesce((
      select jsonb_agg(jsonb_build_object(
        'source', source,
        'medium', medium,
        'sessions', sessions
      ) order by sessions desc, source)
      from acquisition_mix
    ), '[]'::jsonb),
    'searchSurfaces', coalesce((
      select jsonb_agg(jsonb_build_object(
        'surface', surface,
        'searches', searches,
        'averageQueryLength', average_query_length,
        'averageResults', average_results
      ) order by searches desc, surface)
      from search_surfaces
    ), '[]'::jsonb),
    'dataQuality', jsonb_build_object(
      'timezone', 'Asia/Ho_Chi_Minh',
      'seriesCappedAtDays', 180,
      'collectionStartedAt', (select min(created_at) from public.app_analytics_events),
      'consentModel', 'opt-in anonymous analytics',
      'privacyBoundaries', jsonb_build_array(
        'no raw IP address storage',
        'no search text storage',
        'no query-string storage',
        'staff and admin routes excluded',
        'aggregate staff reporting only'
      )
    )
  )
  into v_payload;

  return coalesce(v_payload, '{}'::jsonb);
end;
$function$;

revoke all on function public.staff_product_analytics_report(date, date, date, date) from public;
revoke all on function public.staff_product_analytics_report(date, date, date, date) from anon;
grant execute on function public.staff_product_analytics_report(date, date, date, date) to authenticated, service_role;

notify pgrst, 'reload schema';
